### ISSUE TITLE
Explore Hive with SSL

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#10108]
**Affected module**
Ingestion Framework

**Describe the bug**
we use `pyhive` to load the metadata from hive source. It does not seem to do a great job when there is a hive server with ssl enable, explore the `pyhive` alternatives or explore steps to configure pyhive with ssl.

**Comment by gmedici** [comment]
As of this regards we had the same problem of connecting to hive with ssl and kerberos authentication.
The fix that we tested to use pyhive for the connection was to pass a custom thrift_trasport object to `hive.Connection` , configured with TSSLSocket. This worked.

You could add a specific hive+ssl option on the connection scheme drop in the "Edit Service Connection" page so that, if choosen,  you could construct this object and pass it to the pyhive connection constructor to make it work for ssl too. 
```
...
socket = thrift.transport.TSSLSocket.TSSLSocket(host, port, cert_reqs=CERT_NONE)
thrift_transport = thrift_sasl.TSaslClientTransport(sasl_factory, sasl_auth, socket) 
```

However it would be nice if you could also explore using [impayla](https://github.com/cloudera/impyla) as a connection library in alternave to pyhive to cover also http and https as per #7793 

Impayla covers hive and impala too and has a SqlAlchemy connector and its back by Cloudera.

You might also think about how to approach passing a custom ssl certificate for client validation too, or toggling the validation on/off.

**Comment by harshach** [comment]
can this be solved by impalya driver cc @ulixius9

**Comment by ulixius9** [comment]
Yes closing by https://github.com/open-metadata/OpenMetadata/pull/10270
