### ISSUE TITLE
Eliminate entity reference and use FQN in the topology

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#10133]
After the https://github.com/open-metadata/OpenMetadata/pull/10124 is merged.
Remove the use of entity ref while processing topology nodes and add FQNs in the context and use them

**Comment by codingwithabhi** [comment]
Hi @OnkarVO7 
Using `FQN` or `name` in the context is affecting the performance, as this is increasing the API calls to fetch the table entity. We are using the `table_id` here to create an [OMetaTableConstraints](https://github.com/open-metadata/OpenMetadata/blob/55d5b4ed7c58bff2ad0a3887e2163fa69e205c14/ingestion/src/metadata/ingestion/source/database/common_db_source.py#L419) object. We are also extracting `name` from `FQN` at multiple places, because we require both `name` and `FQN` to create request. Check here for [name Ref ](https://github.com/open-metadata/OpenMetadata/blob/55d5b4ed7c58bff2ad0a3887e2163fa69e205c14/ingestion/src/metadata/ingestion/source/database/common_db_source.py#L252) and [FQN Ref](https://github.com/open-metadata/OpenMetadata/blob/55d5b4ed7c58bff2ad0a3887e2163fa69e205c14/ingestion/src/metadata/ingestion/source/database/common_db_source.py#L171)
`EntityReference` will help us to fetch those values efficiently.
