### ISSUE TITLE
Table search is not working for partial search words 

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10224]
**Affected module**
UI

**Describe the bug**
Table search is not working for search words which are a part of complete word. e.g.: 
1. search word : 'license' from the table name 'driverlicense'
2. search word: telematics from the table name :  [int_nigeria_mixtelematics_assest_events]

**To Reproduce**

Screenshots 
before 

![image](https://user-images.githubusercontent.com/110607559/219345926-86b095fb-d15c-4a76-aed9-e2b081640ef2.png)

after 

![image](https://user-images.githubusercontent.com/110607559/219346024-4f33bf15-c4d2-4f35-836d-f136f8ce4ca4.png)

**Expected behavior**
It should look for parts of word too

**Version:**

 - OpenMetadata version: [e.g. 13.2]

**Comment by ayush-shah** [comment]
@harshach do we need any changes from the UI side? cc: @open-metadata/ui

**Comment by harshach** [comment]
yes @chirag-madlani we are not passing wild-cards *driver* or *license* etc.. and also for exact match users can pass "driverlicense" , UI doesn't support this

**Comment by harshach** [comment]
this issue is fixed and should be available in 0.13.2 as well
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/224503091-c5df7f88-42cf-46b8-9cb3-2316d7626c83.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/38649/224503104-54eddcd0-0f0d-4206-bad3-85a2f639e5f8.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/224503121-2d927171-21d4-42c0-a269-e5f022da982b.png">
@lailapatel give it a try with latest 0.13.2
