### ISSUE TITLE
Some Pipelines are not getting ingested from airflow 2.5.1

### ISSUE THREAD

**Issue by stepanof** [open-metadata/OpenMetadata#10423]
**Affected module**
Ingestion Framework

**Describe the bug**
OM 13.2
OM Airflow 2.3.3
My Airflow 2.5.1

I have added my airflow as source for Pipeline Service. 
In connection I choosed 'Postgres Connection' for 'Metadata Database Connection' option, defined host, port, user, password.
Then I added weekly ingestion and deployed ingestion to OM Airflow.

Some DAGs are getting ingested, but some DAGs cause fatal error. Log [is attached.](https://github.com/open-metadata/OpenMetadata/files/10883882/debug_log.txt)

**To Reproduce**

Described above

**Expected behavior**
All DAGs should be ingested successfully

**Version:**
 - OS: ubuntu 20+
 - Python version: 3.10
 - OpenMetadata version: 13.2

**Comment by poohdini1994** [comment]
**Issue:**

I'm trying to enable ingestion of lineage metadata from airflow into OMD and I followed your documentation (https://docs.open-metadata.org/connectors/pipeline/airflow/lineage-backend).

1. Installed openmetadata-ingestion library
2. Added environment variables for docker file
3. Defined inlets and outlets using guid tables in OMD

I'm getting following errors "AttributeError: 'BashOperator' object has no attribute '_inlets'. Did you mean: 'inlets'?"
And error appear in 2 scripts "backend.py" and "xlets.py"!

**Version:**

Python version: 3.10
OpenMetadata version: 13.2.0
Airflow version: 2.5.0

**Comment by Amanraj0007** [comment]
Affected module
Ingestion Framework

Describe the bug
OM 13.2
My Airflow 2.5.0 (self hosted)

I have added my airflow as source for Pipeline Service.
In connection I choosed 'Postgres Connection' for 'Metadata Database Connection' option, defined host, port, user, password.
Then I added daily ingestion and deployed ingestion to Airflow.

Some DAGs are getting ingested, but some DAGs cause fatal error. Log is
Affected module
Ingestion Framework

Describe the bug
OM 13.2
My Airflow 2.5.0 (self hosted)

I have added my airflow as source for Pipeline Service.
In connection I choosed 'Postgres Connection' for 'Metadata Database Connection' option, defined host, port, user, password.
Then I added daily ingestion and deployed ingestion to Airflow.

Some DAGs are getting ingested, but some DAGs cause fatal error. Log [is attached.](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Amanraj0007/openmetadata/blob/main/log.txt)

To Reproduce

Described above

Expected behavior
DAGs should be ingested successfully

Research:
Dags configuration json file is getting created under dag_generated_configs directory
Dags code python file is not getting created under dags folder.

here are the logs 


Version:

- OS: Amazon Linux 2
- Python version: 3.8.15
- OpenMetadata version: 13.2
- openmetadata-managed-apis:  0.13.2.8
