### ISSUE TITLE
Consolidate Metadata -> OpenMetadata settings under one section

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10614]
**Feature**
OpenMetadata Service comes under Metadata -> Services. 
OpenMetadata Service is a system-level service; we do not want to show this under Metadata Services.

1. Create a section of OpenMetadata
2. under OpenMetadata we need following sections 
     1. Search
     2. DataInsights
     3. Email
 3. DataInsights should've a pipeline deployment. We need to document in main DataInsights page if we do not have a pipeline deployed. We should show relevant documents and ask users to deploy by going to these settings page
 4. Search, similar to what we have currently, where users can trigger on-demand but we also need allow users to deploy the Pipeline to periodically schedule the indexing
 5. Email, all of email settings in config right now. It is hard to configure that way we should move all of the settings to the UI.

**Describe the task**

**Comment by chirag-madlani** [comment]
@harshach this will be P1 right?

**Comment by chirag-madlani** [comment]
Error messages that needs to be print out:

For Case 1:
Unable to connect to Elasticsearch cluster. Ensure that your search cluster is up and running.
Case 2A - User is Non Admin
Unable to serve the request due to search indexing issues. Please contact your Admin.
Case 2B - User is Admin
Unable to serve the request. Navigate to Settings -> Elasticsearch and run full re-indexing.

**Comment by aniketkatkar97** [comment]
@harshach, I and @mohityadav766 need clarification about the requirements here. Can we have a discussion about this?

**Comment by harshach** [comment]
@chirag-madlani I think only remaining work is to provide the doc links and helpful text

**Comment by chirag-madlani** [comment]
Yes that's only pending
