### ISSUE TITLE
test definition allows "-", but Test Name considers that a special character

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10705]
**Affected module**
UI, Test Definition and Test Result

**Describe the bug**
I have created a custom test definition via API:test-definition-1. So dash character is allowed
 I am creating a table test, and suggested name combines "table name" and "test definition name".  However, as test definition contains a dash, this becomes an invalid name,

**To Reproduce**

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/26750060/226877721-308f1279-e33b-493f-b8e5-57cbd0676217.png)

**Expected behavior**
dash is consistently allowed or not allowed in the entity name.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 13.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeodorLungu** [comment]
Can I be assigned to this issue?

Since the custom definition for test allows dash (-) characters, and in the UI, the suggested name combines the table name with the test type, I think it should be allowed to have a dash character, therby modifying the allowable character regex in TestCaseForms.tsx. If there are any other suggestions for how to fix this (perhaps by disallowing the dashes in the test case definition, or by stripping the dashes when combining the names), I am open to hearing it out!

**Comment by sureshms** [comment]
@TeodorLungu assigned the issue to you. @Sachin-chaurasiya can you address the question from @TeodorLungu above?

**Comment by harshach** [comment]
@TeodorLungu what you proposed makes sense to me. Feel free to change the specification to allow these characters. Let us know if you have any questions

**Comment by chirag-madlani** [comment]
This is working fine with 1.2.3 release
