### ISSUE TITLE
quicktype type generation is failing without any error being printed

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#10811]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI -- Build

**Describe the bug**

- Quicktype type generation step on UI is failing without printing any errors. 
- We should have clear messages if any types fail to create and should not block the thread itself.
- Currently of failing types step is being blocked

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by phalix** [comment]
There are several issues with the quicktype generation right now.

First emailVerificationToken defines the following:
"required": [
        "token",
        "user",
        "tokenType",
        "tokenStatus",
        "expiryDate"
    ],

Though there is no type user, but a type userid. 

In addition the $id of several classes do not match the path they are actually in. E.g. createWebAnalyticEvent.json defines the $id as https://open-metadata.org/schema/api/tests/createWebAnalyticEvent.json, though the actual path is /api/analytics/createWebAnalyticEvent.json.

Lastly, I ran into problems due to the usage of https://open-metadata.org in the id, which caused the quicktype generator to constantly do http request, which also lead to blocked requests. 

If you want to have a detailed log of the generation, you can always --debug all on the quicktype command on json2ts.sh:
./node_modules/.bin/quicktype -s schema $PWD"/${schema_directory}$1" -o $PWD"/"$om_ui_directory$2 --just-types --debug all > output.log 2>&1

Also I put the output to a file.

**Comment by Sachin-chaurasiya** [comment]
Fixed with this https://github.com/open-metadata/OpenMetadata/pull/12335 PR.
