### ISSUE TITLE
Build Automations Application

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#11370]
Automation App will be critical for our next iteration of the vision behind OpenMetadata.
The goal is to add pluggable Automation into OpenMetadata.
Few Examples are
1.  Delete older data in entity_extension_time_series
2. Propagate tags and descriptions based on Lineage
3. Generate Data Insights
4. Index Metadata Change Events like we are doing now

**Automation App(lication) Manifest**
1. Identity: Which bot identity does the app use? Currently, we are using an ingestion bot for everything. Each Automation should come with its own identity, thus providing a bot user for it. Automation can be treated as an App
2. Execution Mode: Live, Scheduled, Externally Scheduled. What type of execution mode does the App provide? It could be live as the metadata change events come in. They are processed and executed in the server context or they can be scheduled. They can be a scheduled thread that wakes at configured time frequency and does its job or it can be externally scheduled to run as a workflow similar to ingestion
3. Configuration. Each App should have a configuration similar to how we modeled the Service Connection. 
4. Identity Bundle: Each App should register the permissions it requires. Similar to Slack App registration

**Automation App Registration**

1. API Endpoint to register the Automation Applications. This registration is to show the available Applications and a description of what it does
2. UI will show a list of available Automation Applications. Think of it as a marketplace. For starters, this Marketplace is localized i.e. we show available Automation Applications for Starters
      1. Search Indexing Automation App
      2. Delete Older data in entity_extension_time_series. This will allow admins to set an expiry time on metadata versions, data profiler results, etc..
      3. Data Insights generation App
 3. App Registration bundle includes the class name of the Java class where it has all the logic. This is internal details stored as part of app registration and not shown to the User.
 4. App Registration bundle will include a manifest file. This manifest will tell the user(Admin) of what data App is accessing and what bot name it will be using to run the App.  Taking inspiration from the Slack app installation, the information in the manifest file will be shown to the Admin like below 
![image](https://github.com/open-metadata/OpenMetadata/assets/38649/5fd7a183-dde4-433e-a210-dd5ead06a79d)
5. Once the admin approves, during the registration, the backend will enable the app along with the scheduled interval. It uses manifest file permissions to create a bot and creates a policy to allow the reading/editing of entities based on the manifest.

**Automation App Installation**
1. Admins can go to Settings ->  Automations - Add new Automation
2. By default, we will enable SearchIndex, DataInsights generation App
3. Admin can enable Delete Older data
6. When enabling, the App will create the bot identity and bot policy it needs as the admin user
7. If its execution mode is Live, Admin doesn't need to do anything further
8. If its execution mode is scheduled or externally scheduled, Admin will go through additional UI steps to enable the App at a scheduled time

**App Page**
 1. App page will show the current status and historical runs, for live mode, we will show the last known status. Essentially, it's a feed of past runs. We will keep the last 30 days, and older historical runs will be deleted.
 2. Admin should be able to know what actions are performed by the App as an aggregate
 3. Admin should be able to invoke the App on demand
 5. Admin can disable the App
 

** Only Admins will be the ones who can register, enable, and disable applications **

**Comment by pmbrull** [comment]
linking here existing resources we are using related to automations, since we leverage similar ideas for the `Test Connection`:
- automation workflows resource ([link](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/resources/automations/WorkflowResource.java)). We can create, update, delete, trigger,...
- automation workflows spec ([link](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/automations/workflow.json)):
  - Each workflow has a generic `request` and `response` that need to be defined in each case. A `Test Connection` has a specific payload that might be different from a `reindex` automation.
  - Each workflow has a `status` that the UI can use to check if things are `Pending`, `Running`, `Failed,`...
- Data is stored in the `automations_workflow` table. We might need to revisit which workflows need to be kept, deleted, etc. E.g., we want the `Test Connection` automations to be deleted after usage, no point on keeping the history
