### ISSUE TITLE
OM Airflow lineage use of inlets/outlets is not compatible with Airflow Lineage and other airflow features for airflow >= 2.4

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#11626]
**Is your feature request related to a problem? Please describe.**
OM Airflow lineage use of inlets/outlets is not compatible with Airflow Lineage and other airflow features for airflow >= 2.4

**Describe the solution you'd like**
[Discussion RE airflow lineage.](https://openmetadata.slack.com/archives/C02B6955S4S/p1684264026611629)

Dataset aware scheduling uses `outlets`
https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html

Lineage documentation (experimental) but some MUST docs
https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/lineage.html
```Inlets can be a (list of) upstream task ids or statically defined as an attr annotated object as is, for example, the File object. Outlets *can only be* attr annotated object```

Airflow lineage entities
https://github.com/apache/airflow/blob/main/airflow/lineage/entities.py

Dataset is `attr` annotated obj...
https://github.com/apache/airflow/blob/main/airflow/datasets/__init__.py

I expect that we will make heavy use of Dataset aware scheduling. We need to understand how the `dict` based lineage of OM will interact with or conflict with the `attr annotated` requirement of airflow Lineage.

**Comment by gavin-denyse** [comment]
Please prioritize this enhancement.
Thank you!

**Comment by pmbrull** [comment]
hi @kputland @gavin-denyse I could use some more info on the expected usage here:

### Inlets & Outlets
For OM the lineage we get out of Airflow is an edge between two nodes. This means that we need both inlets and outlets in order to draw the `Table A -> DAG X -> Table B`. Are you going to just use the `outlets` on your tasks?

### Identifying entities
Based on the provided links I see that the `Dataset` object can be what seems to me as an arbitrary URI:
- `Dataset("s3://dataset-bucket/output.csv")`
- `Dataset("snowflake://my_db.my_schema.my_table")`

Since you are using - or planning to use - this feature, you might have some more knowledge about the typical use case. What would be a reliable way of identifying the Entity type?
- `Dataset("s3://dataset-bucket/output.csv")` -> This would be a `Container`
- `Dataset("snowflake://my_db.my_schema.my_table")` -> this would be a `Table`

I guess we could use ES to try to fetch the asset in OM querying by name, but we would first need to identify the asset type.

Not sure how much of a stretch would be to consider `s3`, `adls` and `gcs` as the protocols for containers and the rest as tables.

Thanks

**Comment by kputland** [comment]
The point here is not for OM to use Dataset, but for OM to use attr annotated objects instead of the dict method. The current dictionary method of passing the tables names should be replaced by use of the lineage entities found in https://github.com/apache/airflow/blob/main/airflow/lineage/entities.py which include Table, Column, and File. According to the [lineage documentation](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/lineage.html) `Outlets *can only be* attr annotated object` 

The inclusion here of Dataset was for reference that airflow 2.6 is now using `outlets` internally to implement [Dataset aware scheduling](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html) and that OM should follow the documentation and utilize the attr annotated objects instead of dict to ensure that there are not conflicts with other airflow features.

**Comment by pmbrull** [comment]
ok thanks. Since airflow's requirement is to use an `attr annontated object`, would it be ok to use a custom one instead of https://github.com/apache/airflow/blob/main/airflow/lineage/entities.py?

Bridging their structure to the info we need for OM looks like a patch
