### ISSUE TITLE
Feedback on new UI

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#11737]
https://www.figma.com/proto/3WMvzbwMjj0h4DGrdmEurh/Rupesh---OpenMetadata?page-id=165%3A4153&node-id=820-16517&viewport=-5130%2C-968%2C0.46&scaling=scale-down&starting-point-node-id=447%3A15509&show-proto-sidebar=1

- it appears too noisey when hovering over a button, would prefer if icon and text don't move
- what's the experience for users (non-admins) for homepage? do they also see KPIs, total data assets, pipeline
- annoucements should be at the top above following / recently viewed. It shouldn't move BTF.
- I like quick links. What's the experience here for the admin, can we configure the content?  
- I still don't think the feed is relevant for users (for our Enterprise organization). I would like to see more developments towards Quick links / introduction etc that guide the user. Feeds are very confusing for Enterprise organization where we don't have much control over who happens to access the portal (from outside the org).

**Comment by sureshms** [comment]
> it appears too noisey when hovering over a button, would prefer if icon and text don't move
Not sure which elements you are talking about. Please do look at 1.1 and we can have the discussion in the #UX-Designs channel.

> what's the experience for users (non-admins) for homepage? do they also see KPIs, total data assets, pipeline
We don't have pipelines yet. But the experience for non-admins is as shown in the design.

> annoucements should be at the top above following / recently viewed. It shouldn't move BTF.
That is the case in the updated designs

> I like quick links. What's the experience here for the admin, can we configure the content?
Yes

> I still don't think the feed is relevant for users (for our Enterprise organization).
Collaboration using activity feeds is a key differentiator for OpenMetadata. It is widely used within our community based on the feedback. It not only covers Activity Feeds and Mentions but also Tasks, another key collaboration feature.

> Feeds are very confusing for Enterprise organization where we don't have much control over who happens to access the portal (from outside the org).
I don't understand what the issue here is. Not sure what the control issues or are why accessing the portal from outside the org results in problems.

Let's continue this discussion in #UX-designs channel on Slack after 1.1 is released. I am closing this issue as it has bunch of feedback and questions.
