### ISSUE TITLE
backend: duplicate policy and rule related bugs

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#11860]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**

- [x] The duplication check is not working while creating a policy with the same name as the system-generated policy. The check works when user-created policies are conflicting.
Request URL: `/api/v1/policies`
Method: `POST`

https://github.com/open-metadata/OpenMetadata/assets/51777795/5b4d606d-a5eb-40a3-a0dc-b9d92267f2f0

- [x] Duplicate rules can be added to the same policy with the same name. Also after editing one of them, all the rules with the same name are updated.
Request URL: `/api/v1/policies/{id}`
Method: `PATCH`

https://github.com/open-metadata/OpenMetadata/assets/51777795/51547f09-5e36-4466-b521-e42b5b5a43c5

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohityadav766** [comment]
@aniketkatkar97 it's not that you are using the same name , actually OrganizationPolicy Create by system has the display name as "Organization Policy" but the name as "OrganizationPolicy" , while the new entity you created has the name as "Organization Policy" , since the changes of fqnHash Hash("OrganizationPolicy") != Hash("Organization Policy").  the other rule issue seems valid and fix for that is in this PR :- https://github.com/open-metadata/OpenMetadata/pull/13883
cc @harshach 
Please see the below video :- 

https://github.com/open-metadata/OpenMetadata/assets/105265192/7d0d4e6b-1f7c-4352-b7ed-29677e8a11fd
