### ISSUE TITLE
Tables with large numbers of columns are unusably slow

### ISSUE THREAD

**Issue by cutz** [open-metadata/OpenMetadata#12373]
**Affected module**
UI and Backend

**Describe the bug**
I have tables with nearly 1,000 columns in them, and currently I have some use cases where it would be convenient to have double or triple that. With a table with close to 1000 columns the UI is unusable in safari running on top-of-the line mac hardware. The lack of paging makes for slow requests to the server, but even once fetched, the browser essentially locks up. 

Chrome is significantly better. The request to the server is still quite slow, but once loaded the UI is still usable. Are there any open initiatives to improve performance for large numbers of columns in tables? Has there been any consideration of using a virtual list for that table?

**To Reproduce**

Create a table with 1,000 columns and look at the schema for that table in the UI. Note the page takes a very long time to load note that safari locks up. Chrome doesn't lock up, but the initial request and render is still quite slow.

**Expected behavior**

The UI should function in a performant way when columns have 1,000+ columns.

**Version:**
 - macOS 13.4.1 (22F82)
 - Safari 16.5.1 
 - OpenMetadata 1.1.0

**Additional context**

Link to [discussion on slack](https://openmetadata.slack.com/archives/C02B6955S4S/p1689101152941579).

**Comment by joegoldbeck** [comment]
Relatedly, adding column _tags_ starts to fail as well once there are a large number of tagged columns. 

I believe this is because each tag is fetched from the database individually, requiring hundreds of database calls just to get the table. https://github.com/open-metadata/OpenMetadata/blob/02094179e6ae92abba919f9bc888d57f6389421e/openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java#L2160-L2168

I tested GETing the table with and without tags in the `fields=` and it is specifically `tags` that causes the backend to be super slow (4s just for GET table).

I suspect there are some simple backend optimizations that would solve this. The most immediate solution would be to fetch many tags in a single db call.

**Comment by harshach** [comment]
@mohityadav766 we can change the tags query to bring all the tags at one go using the FQN prefix and also join with Tags and GlossaryTerm to build the right Object out of it . Currently we are making one call per column and also making Tag and GlossaryTerm calls for each tag label. This can ideally be come in one query.
cc @pmbrull we should add some sample data with 1000s of column and each column having 5 tags (combination of tags and terms) to take the measurement

**Comment by mohityadav766** [comment]
Done
