### ISSUE TITLE
Lineage export option in a csv or excel file

### ISSUE THREAD

**Issue by agrawalrajat369** [open-metadata/OpenMetadata#12502]
**Is your feature request related to a problem? Please describe.**
I'm not able to download or export the lineage of a Table/View on the Lineage tab in the dashboard.

**Describe the solution you'd like**
I want to be able to download or export the lineage visible in a CSV or excel file for further review and analysis.

**Describe alternatives you've considered**
NA

**Additional context**
There is another tool called Datahub which provides this feature. Maybe that can be a source/context of reference to implement the feature.

**Comment by tonsumawang** [comment]
Hi OMD Team - Formally requesting to have a feature to export a table/column-level lineage both upstream and downstream to a file i.e. CSV (Please see attached sample).
[application_submitted_Downstream (1).csv](https://github.com/open-metadata/OpenMetadata/files/14108329/application_submitted_Downstream.1.csv)

This is very useful if the Lineage graph is congested with hundreds of upstream and downstream lineages which is hard to trace for Impact Analysis/Root Cause Analysis.
Thank you

**Comment by vianneybacoup** [comment]
Hello @harshach, I would like to know if this feature is still on track for release 1.4.0 ? It's been months without update so just want to confirm. I'm as well looking forward to use it !
Thanks

**Comment by harshach** [comment]
@karanh37 we need to ship this in 1.4.0

**Comment by tonsumawang** [comment]
Thank you @harshach & @karanh37 for including this feature in v1.4! Much appreciated!
