### ISSUE TITLE
Slack alerting bugs

### ISSUE THREAD

**Issue by ruffury** [open-metadata/OpenMetadata#12505]
**Affected module**
UI, backend

**Describe the bug**
1. Message of alert poorly formatted, its hard to understand
![image](https://github.com/open-metadata/OpenMetadata/assets/23666121/bb80bb80-61e8-4b18-bb33-aef676f5490d)
2. URL in alert raise error 404
![image](https://github.com/open-metadata/OpenMetadata/assets/23666121/0bf60199-c474-4732-8abe-796f8d5a32c8)
3. When you specify FQN in filters in alert config - alert is not working
![image](https://github.com/open-metadata/OpenMetadata/assets/23666121/628ba43a-b322-42aa-9889-50aa3580a3dc)

**To Reproduce**
1. Create test suite and test case on any table on Clickhouse (i assume any source)
2. Create alert config like that: 
<img width="1364" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/23666121/49150d04-0a3a-4c87-af13-5860eb2972db">
You need slack channel and incoming webhook for that, so you can specify url in config
3. Run test case manually to get alert in slack
4. You can specify FQN of test case and you won't get any message in slack then

**Expected behavior**
A concise, clear, and informative alert message containing a functional URL.

**Version:**
 - OS: linux
 - Python version: 3.9
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohityadav766** [comment]
hi This is fixed in 1.3.0
We won't be able to format specifically test result for Slack in this release we might look at it in future releases.
This is how it will look for now :- 
![Image](https://github.com/open-metadata/OpenMetadata/assets/105265192/5c827981-e3c3-487b-a445-a3e4f2a9749a)
- Clicking on the Url will take you to the table Data Quality page where the test case belongs
- Alert with FQN is fixed
