### ISSUE TITLE
Password Change Not Validating Old Password

### ISSUE THREAD

**Issue by arudra123** [open-metadata/OpenMetadata#12584]
In the user profile, system is not validating the old password entered by the user when they attempt to change their password. This means that a user can change their password to any value, even if it is the same as their old password.
Steps to Reproduce:
Log in to the user profile system.
Click on the "Change Password" link.
Enter your old password.
Enter a new password.
Enter the new password again to confirm.
Click on the "Update Password" button.
Expected Results:
The system should validate the old password and only allow the user to change their password if the old password is correct.

**Comment by mohityadav766** [comment]
@chirag-madlani can you please assign someone from UI , if the User is updating his own account UI needs to send ChangePasswordRequest SELF for requestType , currently Admins of the system have the privilege to update anyone's password , so for their own password if don't send SELF it won't require the OLD_PASSWORD since the user is already an admin, so please send SELF in case the user updates his own account

**Comment by chirag-madlani** [comment]
@mohityadav766 assigned this to @Ashish8689.
Thanks

**Comment by harshach** [comment]
we are also limiting only certain special characters and max length  is set to 16 chars. We need to increase it cc @mohityadav766 @chirag-madlani

**Comment by chirag-madlani** [comment]
@harshach will rule with @mohityadav766 for this ticket only

**Comment by mohityadav766** [comment]
closing this it handled
