### ISSUE TITLE
fail to display cutom properties of the table

### ISSUE THREAD

**Issue by zwbill82** [open-metadata/OpenMetadata#12682]
**Affected module**
UI

**Describe the bug**
I am trying to add a policy with read-only permissions, but it is not displaying the custom properties of the table.

**To Reproduce**

-  create a policy 

<img width="1106" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/29267289/90fc524d-c40c-447d-99ec-9771a74d1257">

- grant it to Organization

<img width="1138" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/29267289/a4dc2cfd-146f-4055-95b1-e655a06ad4a0">

- an account login, and it did not show the custome fields
<img width="1073" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/29267289/6e5118d9-7a5c-454c-8b94-6366c22215e8">

- if we use 'admin', it can show it.

<img width="1183" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/29267289/f3452309-ef45-4672-be41-7b8ed9033694">

**Expected behavior**
It should show the table's custom properties

**Version:**
OM 1.1.0

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hello @sureshms , I have checked this and it's failing because we are fetching the custom properties of metadata type `table` `http://localhost:8585/api/v1/metadata/types/name/table?fields=customProperties`.

So for custom properties should we fetch metadata types permissions as well and check for viewAll operation?
