### ISSUE TITLE
On-the-fly spacy language model downloading requires allowing access to a lot of GitHub IP addresses

### ISSUE THREAD

**Issue by svroonland** [open-metadata/OpenMetadata#12813]
The Spacy language model is downloaded dynamically for PII classification. In our kubernetes setup, this required a network policy to allow access to a long list of GitHub IP addresses. We would strongly prefer not to have such an open connection from our private network, for data security reasons obviously.

I noticed this dependency was initially built-in but removed in https://github.com/open-metadata/OpenMetadata/pull/1362.

Can we consider adding it back again? Perhaps there is a way to speed up builds.

Or would there be an alternative way to provide the package without having to connect to GitHub?

**Comment by harshach** [comment]
we are not using spacy anymore, cc @pmbrull can you confirm and close this out

**Comment by sharmalokeshk** [comment]
Can you confirm which NLP model you are using right now?

**Comment by pmbrull** [comment]
hi sorry missed this one. We still use `spacy` as the way to run the presidio NLP model here https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/pii/scanners/ner_scanner.py#L53

**Comment by pmbrull** [comment]
@svroonland I believe that you might be able to just write on top of our Ingestion image and download the model on your own. For us it's important to keep the package as small as possible, since not all users would want this functionality. Downloading this by default makes the resulting images quite big

**Comment by svroonland** [comment]
That is indeed what we did to resolve this issue. Thanks for considering.

**Comment by sharmalokeshk** [comment]
@pmbrull I have understood the presidio NLP model and we just added some entities in ner.py which are supported by presidio (see below). But when we ran Profiler ingestion after that it didn't tag related entities. 

#India
    IN_PAN = TagType.SENSITIVE.value
    IN_AADHAAR = TagType.SENSITIVE.value
    IN_VEHICLE_REGISTRATION = TagType.SENSITIVE.value

We changed the code for our virtual env so it should work or we need to make changes somewhere else also.

And if you can help in how we can write column name regex for the above entities and all related changes that would be great.

**Comment by pmbrull** [comment]
hi @sharmalokeshk, having this on the enum you mentioned should be good enough, thanks!. Feel free to open a PR with this change. I am not sure having those into regex might be the best approach since it can become very complicated very easily. Might be safer to rely on presidio's scan of sample data to detect these entities. Note how on the regex rules, we do very basic validations while relying on presidio for complex stuff, such as IBAN codes or other national IDs
