### ISSUE TITLE
Can we choose postgresql instead of mysql while deploying through Kubernetes pods?

### ISSUE THREAD

**Issue by rkothariauto** [open-metadata/OpenMetadata#12822]
Question related with deployment. When we are deploying through Kubernates pods, do we have option to choose postgresql instead of mysql ? Going through deployment documentation here--> https://docs.open-metadata.org/v1.1.1/deployment/kubernetes

**Comment by dhruvinmaniar123** [comment]
Hi @rkothariauto ,

If you are looking for QuickStart setup then I would recommend to go with docker setup using postgres. We are giving options for kubernetes to use any external database and connect with Openmetadata application. In your case it would be postgres. 


Thanks,
Dhruvin.

**Comment by rkothariauto** [comment]
ok thanks @dhruvinmaniar123 so basically its possible to use postgresql as external database only while deploying through Kubernates. Right?

**Comment by dhruvinmaniar123** [comment]
Yes @rkothariauto. If your requirement is to go with kubernetes only then external database is the only option otherwise we have docker with postgres deployment as well that you can download the docker-compose-postgres.yaml from [here](https://github.com/open-metadata/OpenMetadata/releases/tag/1.1.1-release) and follow the steps mentioned [here](https://docs.open-metadata.org/v1.1.1/deployment/docker).
