### ISSUE TITLE
Glossary recursive delete fails

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13049]
with glossaryTerms that have different levels of children

We've observed that a single term tries to be deleted twice, thus raising a 404 in 1.1.2.1

**Comment by harshach** [comment]
This applies to parent child delete. In case of Glossary the relation between Glossary and its nested child terms is confusing. 
We are setting, when we query getChildren of a Glossary all the nested children will come as well , as we walk through this tree, and these nested children can get deleted in recursion and as we comeback we try to delete them again which results in 404

**Comment by sureshms** [comment]
@pmbrull and @harshach, this should be fixed by change #12803, which, during deletion, updates the object to avoid the problem. Let me know if you can still reproduce this.

<img width="1684" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/6a2540c0-eae7-440e-bed8-9939ce3a6f6e">

**Comment by sureshms** [comment]
@pmbrull and @harshach, I could reproduce the problem. So ignore the previous comment.
