### ISSUE TITLE
Define concepts only once and reuse them multiple times

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#13207]
**Is your feature request related to a problem? Please describe.**

Currently a concept is defined again and again. I.e. Address is defined with street number and zip code perhaps. When using this once for a supplier and a second time for a customer - the same structure needs to be defined multiple times. What about om supporting linking a concept in the hierarchy and defining it only once?

**Describe the solution you'd like**
Define the concept once and reuse i.e. apply it over and over multiple times. I.e. use the address both for suppliers and customers but define the structure of the address only once

**Describe alternatives you've considered**
custom CLI to define the OM terms/glossary hierarchy (super complex/annoying) i.e. python script which talks to the REST API -> not business friendly

**Additional context**

- https://openmetadata.slack.com/archives/C02B6955S4S/p1694424335737609
- https://www.youtube.com/watch?v=LII_5CDo_0s

**Comment by pmbrull** [comment]
cc @harshach @sureshms for any comments

**Comment by harshach** [comment]
@geoHeil what are missing in Glossary that can't be achievable what you are after

**Comment by geoHeil** [comment]
When I am in the glossary view i.e. https://sandbox.open-metadata.org/glossary and have the concept address used twice in the hierarchy - once for the customer as customer address and once for the supplier as supplier address I have to define the same concept twice (introduce a duplicate) instead of defining the concept address once and then simply linking/using it multiple times.

What is missing is the possibility to link/reuse a glossary item/concept at multiple places

**Comment by harshach** [comment]
@geoHeil why not use related terms? Yes you still need to create but you can just refer to them as same concepts no?

**Comment by SabineGl** [comment]
Because its not "related" - eg. a street name is part of an address. Its not related - Its a hierarchical relationship like explained here:
https://www.youtube.com/watch?v=LII_5CDo_0s  
And I want to link this business term to a physical entity. I cant do that within a related term. Because then I do not understand if I see a connection from a physical street name (or any other term) to which hierarchical relation ship it belongs. 

Besides that the related terms is not very clear to read. A hierarchical relationship is much better to understand and readable at the first sight.

**Comment by SabineGl** [comment]
![Hierarchical_Relationships_in_OM](https://github.com/open-metadata/OpenMetadata/assets/130458131/7166f7e4-a48e-41a4-af4f-821386be62e9)
