### ISSUE TITLE
PUT method /api/v1/topics - not changing description field 

### ISSUE THREAD

**Issue by etele** [open-metadata/OpenMetadata#13259]
**Affected module**
backend

**Describe the bug**
Using PUT method on `/api/v1/topics` to update a topic, changing the `description` field, does not changes the description.1

**To Reproduce**

Using the PUT/POST method to create a topic:
```
> PUT /api/v1/topics HTTP/1.1
> Host: openmetadata:8585
> Content-Type: application/json
> Accept: */*
> Content-Length: 129

| {
|   "name": "test-topic-bug-reproduce",
|   "partitions": 1,
|   "service": "kafka-service-test",
| 	"description": "original value"	
| }

< HTTP/1.1 201 Created
< Date: Mon, 18 Sep 2023 12:52:31 GMT
< X-OpenMetadata-Change: entityCreated
< Content-Type: application/json
< Content-Length: 840
```

```
> PUT /api/v1/topics HTTP/1.1
> Host: openmetadata-staging.fulltext-dev.ko1.os.scif.cz:8585
> Content-Type: application/json
> Accept: */*
> Content-Length: 128

| {
|   "name": "test-topic-bug-reproduce",
|   "partitions": 1,
|   "service": "kafka-service-test",
| 	"description": "changed value"	
| }

< HTTP/1.1 200 OK
< Date: Mon, 18 Sep 2023 12:54:00 GMT
< X-OpenMetadata-Change: entityNoChange
< Content-Type: application/json
< Content-Length: 939
```

response:
```json
{
	"id": "48ebcade-717f-488a-9370-1caf96901df5",
	"name": "test-topic-bug-reproduce",
	"fullyQualifiedName": "kafka-service-test.test-topic-bug-reproduce",
	"description": "original value",
	"version": 0.1,
	"updatedAt": 1695041551221,
	"updatedBy": "ingestion-bot",
	"service": {
		"id": "c82e2d03-5817-44b5-8f9c-c0e9cabe8bbc",
		"type": "messagingService",
		"name": "kafka-service-test",
		"fullyQualifiedName": "kafka-service-test",
		"description": "kafka-service-test",
		"displayName": "kafka-service-test",
		"deleted": false,
		"href": "http://openmetadata:8585/api/v1/services/messagingServices/c82e2d03-5817-44b5-8f9c-c0e9cabe8bbc"
	},
	"serviceType": "Kafka",
	"partitions": 1,
	"cleanupPolicies": [],
	"retentionSize": -1.0,
	"href": "http://openmetadata:8585/api/v1/topics/48ebcade-717f-488a-9370-1caf96901df5",
	"changeDescription": {
		"fieldsAdded": [],
		"fieldsUpdated": [],
		"fieldsDeleted": [],
		"previousVersion": 0.1
	},
	"deleted": false
}
```

**Expected behavior**
Expecting the description field to be changed.

**Version:**
 - OS: Debian 11
 - Python version: 3.9.13
 - OpenMetadata version: [1.1.0]
 - OpenMetadata Ingestion package version: [e.g. **`openmetadata-ingestion[docker]==1.1.0.5`]**

**Additional context**
Its possible to change with the PATCH method using jsonPatch object, but the PUT should do the job too, if it accepts the description field, it should change it.

**Comment by harshach** [comment]
@etele we do not allow bot accounts to override the existing description. This is by design

**Comment by etele** [comment]
@harshach 
If its a design decision then it fails in 2 ways
1. it the model of update should not have that attribute, its misleading having it there
2. the PATCH method allows to modify this field, so eve if you dont want to allow bots to override it, you still allow it with PATCH

thanks for your reply

**Comment by harshach** [comment]
@etele its taken into account of how the ingestion framework works today.
The design decision we are talking about here is following

1. OpenMetadata allow users to update descriptions through markdown. You can add much richer description from OM UI compare to anywhere else , ex: snowflake or dbt etc..
2. Ingestion will pull all the descriptions from the source if there are no descriptions being set in OpenMetadata
3. The reason for this decision is not to override user supplied documentation by default. We believe user supplied / carefully constructed documentation is better than what something may have captured in source table as comments.
4. Apart from above, OpenMetadata provides lot richer features for requesting descriptions, tags from the UI. This enables teams to crowd source documenting the assets right with-in the UI. Not just the engineers but business users, data consumers can contribute to the documentation

Our goal here is to encourage teams to use OpenMetadata to get better description from various personas in an organization not just engineering team.

So if there is a description that exists we don't want to override that by default, because of above reasons.

Now there might be teams who prefer forcing the description, to support that use case , we support that through PATCH call instead of PUT call override. Someone consciously making this decision to override rather hitting a PUT call and accidentally overriding carefully built documentation by a user in OpenMetadata.  PATCH is better approach here because the api caller must make a decision on exactly what specific field they are updating.

Having said that in our connector configuration we have an option to force it. But if you are using API calls directly and using ingestion bot token you'll be running into above design decision.

We are enabling user token's in 1.2 release and you can use user's token to use PUT apis to override if that fits your usecase.

This has been discussed many times :) feel free to hop into [slack](https://slack.open-metadata.org )
