### ISSUE TITLE
Search on database schemas

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#13276]
**Is your feature request related to a problem? Please describe.**
It's impossible to search on database schemas

**Describe the solution you'd like**
Maybe a new Elasticsearch index on database schemas or include schemas to table index. The end result is to search on schemas. 

**Describe alternatives you've considered**
No alternatives 

**Additional context**
Why it's important. In DWH schema is very important part of data discovery. User should have a chance to find all tables in a particular schema.

**Comment by harshach** [comment]
@gnomolio do you want to see database schemas as another option in explore left side panel? or do you want to search for tables that belong to a schema?

**Comment by ttjmartinez** [comment]
Hi, we started recently using OpenMetadata and we face a similar need. We try to assign ownership at the Database Schema level when possible rather than at the table level, so one of the most common searches is to find who is the owner of the schema. Right now is quite tedious to find it since schemas themselves are not searchable in the user interface. Users need to select a database and then scroll through multiple pages of schemas in order to find it.
