### ISSUE TITLE
Alerts - no alert raised when a User is created or deleted

### ISSUE THREAD

**Issue by ruth-mills-naimuri** [open-metadata/OpenMetadata#13373]
**Affected module**
UI (and possibly backend)

**Describe the bug**
Alerts - no alert raised when a User is created or deleted.

**To Reproduce**
Add an alert within OM's UI for "User Created or Deleted":
- Trigger: User
- Filter: Event Type - Entity Created, Entity Deleted, Entity Soft Deleted - Include
- Add a valid Slack webhook or email integration with "Send to: Admins" ticked.

**Expected behavior**
When a new user is created in OM, then an alert should be received via Slack or email to say that the user has been created.

**Version:**
 - OS: macOS Ventura 13.6
 - Python version: 3.9.18
 - OpenMetadata version: 1.1.5
 - OpenMetadata Ingestion package version: 1.1.5

**Additional context**
The issue is that no alert is being received when a user is created or deleted within OM.

**Comment by harshach** [comment]
To Reproduce
Configure an alert as follows:

Trigger: tick "All".
Filter: Event Type - Entity Created, Entity Updated, Include
Add a valid Slack webhook or email integration with "Send to: Admins" ticked.
Change the owner of an entity within OM to a user within OM.
Delete the user who you just changed the entity to be owned by.
Expected behavior

An alert should be received stating that the entity's owner has been changed from the deleted user to "No Owner".


To Reproduce
Configure an alert as follows:

Trigger: untick "All", tick all of the sub-options within "All".
Filter: Event Type - Entity Created, Entity Updated, Include
Add a valid Slack webhook or email integration with "Send to: Admins" ticked.
Create a new Container or modify an existing Container within a storage service in OM.
Expected behavior

"Container" should appear in the list of entities within the "Trigger" section of the alert (if "All" is deselected).
It should be possible to select "Container" as the only entity type within the trigger, and "Event Type === entityCreated, entityUpdated" for the filter, together with a valid Slack or email integration.
When a new Container is created, or an existing Container is updated, an alert should be received via Slack or email
