### ISSUE TITLE
PUT api of Model doesn't reflect changes

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1360]
Try updating `description` using PUT method, it does not reflect changes

**Comment by harshach** [comment]
@darth-coder00 this is by design
1. ingestion inputs from source the description it can get
2. lets say now Model has "description1"
3. User comes in now changes Model's description to "description2"
4. Next run of ingestion runs and it will try to update the description with "description1" which will overwrite users' changes

We are giving priority to user's changes vs ingestion. It will be the same across the entities
cc @sureshms
