### ISSUE TITLE
Index not found exception should prompt users to reindex

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#14417]
we get this request a bunch of times in the community. Let's update the backend exception messages to make it easier to solve for users

**Comment by chirag-madlani** [comment]
@pmbrull some details will be more helpful, Not sure when we are encountering this issue

**Comment by harshach** [comment]
@chirag-madlani if the users didn't setup search cluster properly , previoulsy we get a index not found exception
<img width="1605" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/bdd88c0c-6fc3-4b88-8d9d-d83b144fa832">
Instead of throwing this error we should provide a red error message ( check rupesh's mocks) and provide a proper error message and also ask users go to Settings -> Applications -> SearchReindexing Application -> Configure ( a direct link would be better) and ask them to click on "Run Now" to re-index

**Comment by harshach** [comment]
@chirag-madlani added errorType for UI to process the errors better and throw meaningful errors back to the user https://github.com/open-metadata/OpenMetadata/pull/14784

**Comment by Abhishek332** [comment]
@chirag-madlani Can you assign this issue to me

**Comment by ShilpaVernekar** [comment]
@Abhishek332 - Please check if this message would be fine

**Error:** Indexing Issue
Please navigate to Settings (add link) to click on 'Run Now' to reindex the data.

cc @harshach
