### ISSUE TITLE
Improvement: Data Quality to Support Multiple Pipeline Schedules

### ISSUE THREAD

**Issue by flymemoryRPA** [open-metadata/OpenMetadata#15133]
**Is your feature request related to a problem? Please describe.**
Currently, only one pipeline is available for the same database table, but sometimes I need to run different test cases at different time of the day/or of the week. 
For example, there are 10 test caess. I hope to run test case 1-5 in the morning, and 6-10 in the afternoon.

**Describe the solution you'd like**
I hope we can define if more than one pipeline for the same table, and I can choose which test cases to run in one pipeline.

**Describe alternatives you've considered**
For now, I'm adding "case when" into my custom SQL script to achieve this, but it adds complexity to the script.

**Additional context**
N/A

**Comment by TeddyCr** [comment]
Hey @flymemoryRPA thanks for opening this issue. Could you share more details around your use case for what you mentioned below. 😊

> For example, there are 10 test caess. I hope to run test case 1-5 in the morning, and 6-10 in the afternoon.

**Comment by flymemoryRPA** [comment]
Sure, @TeddyCr . There are two scenarios. 

**Scenario 1**: incremental data are inserted into the table by multiple batches. 
For example, batch 1 arrives in the morning, and batch 2 arrives in the afternoon. 
If we count(distinct(site_code)), in the morning it's 10, in the afternoon it's 14. So, I need to write a case when script to solve this problem. It will be much better if we can split this into 2 test cases. One for the morning check, one for the afternoon check.
```
CASE 
    WHEN EXTRACT(HOUR FROM CURRENT_TIMESTAMP) < 16 AND COUNT(DISTINCT site_code) = 10 THEN 0
    WHEN EXTRACT(HOUR FROM CURRENT_TIMESTAMP) >= 16 AND COUNT(DISTINCT site_code) = 14 THEN 0
    ELSE 1 
  END AS check_value
```

**Scenario 2**: The same table is used by different projects.
We have a transaction table that stores transaction data from multple projects. 
For project A, the check should be at 10am in the morning.
For project B, the check should be at 5pm in the afternoon, as the incremental data is not available until the afternoon.
We cannot wait for 4pm to run the quality check, as project A needs to be checked in the morning.
As a workaround, I added case when into the script, but this is not very scallable if we add more and more projects to be monitored in this table.
```
select case when hour(current_time() ) <17 then 0 when hour(current_time() ) >=17 and count(1)=4 then 0 else 1 end as site_check
from laravel.transactions t where project_id ='RPA-0069' and status='Successful' and group_id = CURDATE()
```

I hope this makes sense. Feel free to let me know if you have questions.

**Comment by tonsumawang** [comment]
Ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1714459325507969 

Suggesting to to have DQ Job Pipeline per Test Suite rather than per Table for the following use cases. This will allow us flexibility in DQ job orchestration/bundling and ease of monitoring and maintenance specially of you are handling thousands of tables.

1. Tables per domain
2. Tables per table type (mart, mapping, master, transaction, related types)
3. Tables own by a Team/Business

For the conflict that a test case might be added in more than 1 test suite or the danger that tables have different ETL refresh timings, this can definitely be manage or rule out with a well orchestrated test suite jobs. Moreover having this test suite job pipelines offers more value than avoiding the said conflicts then having it per table.

User POV expectations for the conflict above, I expect OMD to show me a warning that I am trying to add a test case that was already added in an existing pipeline
OR totally prevent me from adding a test case that already has a pipeline.

**Comment by sushi30** [comment]
requires https://github.com/open-metadata/OpenMetadata/issues/16632

**Comment by harshach** [comment]
@sushi30 is this done?
