### ISSUE TITLE
Helm chart error

### ISSUE THREAD

**Issue by matthew-foreman** [open-metadata/OpenMetadata#15396]
**Affected module**
Helm chart

**Describe the bug**
When importing the helm chart, I get this error: Error: template: openmetadata/templates/secrets.yaml:24:22: executing "openmetadata/templates/secrets.yaml" at \<b64enc\>: invalid value; expected string. It was working the other day, but stopped working yesterday.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Import without error.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by akash-jain-10** [comment]
Hello @matthew-foreman  - 

Request you to raise this [issue in openmetadata-helm-charts](https://github.com/open-metadata/openmetadata-helm-charts/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yaml) with more details to your helm template! That would be the right place for this. Thanks.

Closing the issue here!

**Comment by matthew-foreman** [comment]
I was coming back here to do just that. Thanks!
