### ISSUE TITLE
Template for elasticsearch

### ISSUE THREAD

**Issue by stbogdan77** [open-metadata/OpenMetadata#15543]
Hello. Is it possible to group indexes by templates when working with ElasticSearch data assets? F.e. There are indexes for every day with the same package of fields. So I would like not to describe it day by day again. I see that it is possible to get index templates in https://datahubproject.io/docs/generated/ingestion/sources/elasticsearch (ingest_index_templates: True) <img width="775" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/50769250/fdc21d74-1eed-4c7b-a42d-436b4f03422d">We want to see an implementation similar to the datahub implementation. This would be very convenient. We talk about this https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html 
And this is a widely used case in ELK

**Comment by deathalt** [comment]
It would be nice to see this feature, especially since competitors have it.

**Comment by harshach** [comment]
@deathalt competitiors do not have all the OpenMetadata features either :) 
We introduced search indexes in 1.2.0 and we will evolve those features.
@stbogdan77 @TeXNiZ0 it would be helpful to get some details with examples, instead of posting datahub's screenshots. 
If I understand the feature request correctly
1. Give option to fetch index templates
2. Give option to fetch index templates or individual docs . so that users can pick one or either . Do you see any reason to have both of them ingested at the same time?

**Comment by stbogdan77** [comment]
@harshach  @TeXNiZ0  Hello. To start with, it would be great to add the ability to ingest index templates. In the future, they can be updated if the community wants to add documents and other features.
Templates are needed primarily because indexes are updated regularly, making it impossible to create descriptions and lineage for them as they change every week, whereas templates remain unchanged.

**Comment by harshach** [comment]
@harshsoni2024 Lets prioritize this and work with @ulixius9 on what needs to be done

**Comment by harshach** [comment]
@harshsoni2024 is this fixed?

**Comment by harshsoni2024** [comment]
@harshach, @keshavmohta09 is working on it.
cc @ulixius9
