### ISSUE TITLE
Add Spark Lineage 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1604]
Previously requested the lineage extraction from spark https://github.com/open-metadata/OpenMetadata/issues/1267.
We should target pyspark lineage first than java to extract it from Spark.
@amiorin lets take this as next priority.

**Comment by amiorin** [comment]
@harshach should we close it for now?

**Comment by Taurus-Le** [comment]
Hi there, just to share a piece of information with you.
There's an excellent project called spline which extracts lineage data from spark execution plan.
https://absaoss.github.io/spline/
I've already set it up with docker to gather lineage data of our spark jobs. It provides codeless initialization so that we don't need to modify our codes. And spline is able to send lineage data through http, kafka.
According to the issue below, spline is able to send lineage data in OpenLineage format.
https://github.com/AbsaOSS/spline-spark-agent/issues/354
Currently, I'm figuring how to make spline and openmetadata cooperate with each other. It would nice if you could provide any advice.

**Comment by andbul** [comment]
Hi, is there any plans to add Spark Connector? We have a lot of spark pipelines, that transforms data from to Hive/Hdfs/S3 etc. Previously we were choosing datacatalog, and having spark lineage was one of the top criterias. But now as far as I can see having spark lineage is not in the roadmap

**Comment by ricardogaspar2** [comment]
Yeah this lineage would be a very welcomed and one of kind feature in the data cataloguing space

**Comment by ricardogaspar2** [comment]
Thanks @chirag-madlani for doing this!
