### ISSUE TITLE
Request failed with status code 400 when add ingestion

### ISSUE THREAD

**Issue by velna** [open-metadata/OpenMetadata#1646]
I'm trying to add an ingestion, but got "Request failed with status code 400" each time.
Version: 0.6.0
Airflow: 2.1.4

Here is the request:

```
curl 'http://localhost:8585/api/operations/v1/ingestion' \
-X 'POST' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Content-Type: application/json;charset=utf-8' \
-H 'Origin: http://localhost:8585' \
-H 'Cookie: session=.eJw1kMFqAzEMRP_F58A68tqW91dKWCxZyoZus8F2DqX03-u09CIYNBo95susWqVtZun1KSez3opZDPGsjJn92SZwEOYChYDII4MtHCImy44iBCclklLJwcXhna1mixZTiQ4kUJwhBbJntURFgP1cVDIwuAxZ2RLj-OTYc8Sh1ZOAeDAD5CH1I9_l3v_RuFVd-_Eu90HoY9SQRAdSSvY8I6l3CW1EVQdOPKN_zZFU8nVtPfdnW_W2d6njPO_72OwH512GHJEn88hXWbdb60f9NMub2Xp_LNP0a9qO1heMaKdnk9qmfdgmczmZl_zrDMz3DxRjZnI.YbIJ_g.PZy1KX-mLRqf3MFxDuf7dyMWxkA; VERSION_0_5_0=true' \
-H 'Content-Length: 512' \
-H 'Accept-Language: zh-cn' \
-H 'Host: localhost:8585' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15' \
-H 'Referer: http://localhost:8585/ingestion' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Connection: keep-alive' \
--data-binary '{"ingestionType":"postgres","displayName":"pumpkin","name":"pumpkin","service":{"id":"a3b74a60-63f0-4c5a-8b64-1e5f67c0f413","type":"databaseService","name":"amoros-postgres"},"startDate":"2021-12-09","endDate":"","scheduleInterval":"0 9 * * *","forceDeploy":true,"connectorConfig":{"database":"abc","enableDataProfiler":false,"excludeFilterPattern":[],"host":"readonly.postgres.amoros:5432","includeFilterPattern":[],"includeViews":true,"password":"***","username":"sa"},"owner":{"type":"user"}}'
```

**Comment by amiorin** [comment]
Hi @velna 

```json
{
	"ingestionType": "postgres",
	"displayName": "pumpkin",
	"name": "pumpkin",
	"service": {
		"id": "a3b74a60-63f0-4c5a-8b64-1e5f67c0f413",
		"type": "databaseService",
		"name": "amoros-postgres"
	},
	"startDate": "2021-12-09",
	"endDate": "",
	"scheduleInterval": "0 9 * * *",
	"forceDeploy": true,
	"connectorConfig": {
		"database": "abc",
		"enableDataProfiler": false,
		"excludeFilterPattern": [],
		"host": "readonly.postgres.amoros:5432",
		"includeFilterPattern": [],
		"includeViews": true,
		"password": "***",
		"username": "sa"
	},
	"owner": {
		"type": "user"
	}
}
```

Try to add the ```id``` to the field owner. The [JSON Schema](https://github.com/open-metadata/OpenMetadata/blob/c60a8b56fe252cd887ac919e2b48131d6c2a49f5/catalog-rest-service/src/main/resources/json/schema/api/operations/workflows/createIngestion.json#L25-L29)

**Comment by velna** [comment]
I didn't active the security config, there would be no owner id at all, since none of the authentication methods is an option for our company, are you going to support any other open standards like LDAP or OAuth2.0 ?

**Comment by amiorin** [comment]
There is a bug that we need to fix. The owner is required [here](https://github.com/open-metadata/OpenMetadata/blob/edb2f551d44be4d9eaca9d6f1e6476549a6b1382/catalog-rest-service/src/main/java/org/openmetadata/catalog/ingestion/AirflowUtils.java#L108) but in the JSON Schema can be null. We plan to support all the authentication methods needed by our users. Just drop me a message in Slack so that we collect your requirements.

**Comment by amiorin** [comment]
There is a bug that we need to fix. The owner is required [here](https://github.com/open-metadata/OpenMetadata/blob/edb2f551d44be4d9eaca9d6f1e6476549a6b1382/catalog-rest-service/src/main/java/org/openmetadata/catalog/ingestion/AirflowUtils.java#L108) but in the JSON Schema can be null. We plan to support all the authentication methods needed by our users. Just drop me a message in Slack so that we collect your requirements.

**Comment by sureshms** [comment]
This is very old and may no longer be an issue. @velna, please reopen, if it is still an issue.
