### ISSUE TITLE
What is the reason why the Ingestion framework uses python instead of java?

### ISSUE THREAD

**Issue by Narcasserun** [open-metadata/OpenMetadata#2121]
The maintenance cost of using one language uniformly will be low, I want to know what are the advantages of using both java and python?

**Comment by Narcasserun** [comment]
@sureshms @ayush-shah @harshach

**Comment by harshach** [comment]
@Narcasserun One main reason is
1. Ingestion Framework requires a scheduler to run the these jobs at a scheduled intervals so that we get new metadata frequently
2. Similarly ingestion framework not just limited to fetching metadata but also to run data profiler and tests etc..

In OpenSource we already have very popular schedulers such as Apache Airflow, Prefect etc.. they all are on python and it would be easier for us to integrate into existing scheduler to run these jobs/dags instead of re-building one from scratch.
Also another important thing here is SQLAlchemy , python library which has bindings to pretty much all of the databases . This helps us fetch metadata easier. 
Hope this answers your question.

**Comment by Narcasserun** [comment]
> @Narcasserun One main reason is
> 
> 1. Ingestion Framework requires a scheduler to run the these jobs at a scheduled intervals so that we get new metadata frequently
> 2. Similarly ingestion framework not just limited to fetching metadata but also to run data profiler and tests etc..
> 
> In OpenSource we already have very popular schedulers such as Apache Airflow, Prefect etc.. they all are on python and it would be easier for us to integrate into existing scheduler to run these jobs/dags instead of re-building one from scratch. Also another important thing here is SQLAlchemy , python library which has bindings to pretty much all of the databases . This helps us fetch metadata easier. Hope this answers your question.

Thank you very much for your answer. I have now implemented a metadata management of a multi-data source integrated architecture similar to `Metacat`. I hope to contribute some good features to OpenMetadata later.
