### ISSUE TITLE
Support ability to do access evaluation check on user interface

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2247]
Given a user's name, OpenMetadata should be able to say what permissions the user has. 

As a logged in user, one should be able to tell if they have access to a data asset or to change metadata. And if not, what should they do to gain access.

As an admin, one should be able to use the check to see if a user has permission to access a dataset.

cc: @pmbrull @harshach

**Comment by harshach** [comment]
@mithmatt Ideally we should only have User -> Role relations and from Roles show the policies that they have. That way UI can show what Roles a user have and show the relevant policies

**Comment by mithmatt** [comment]
I'm thinking a bit ahead on this one - we would not need this right away unless users have overly complex rules that it becomes hard for humans to reason about.

When a user has multiple roles (and hence policies), the access given is based on priority of rules across policies. 

User has role A and role B

Role Policy A may have Update Description Deny with priority 100
Role Policy B may have Update Description Allow with priority 500

The evaluation of this would result in Deny since 100 < 500 


PS: It is possible to avoid this scenario with proper guardrails.

**Comment by harshach** [comment]
I am not really looking at this how the policies will evaluated or guarded. More on the side of UX
what is the Role signifies if the User directly have policies? 
Ideal approach for an administrator to group policies into meaningful Roles such that they curate Policies into a buckets of Roles and give users a Role. Otherwise having a policy associated directly to the User we can have direct relation to policy without recognizing what user's role in the system is. 
Example:
 Can a DataConsumer have "UpdateDescription" as a policy , its possible with current APIs. Now imagine if we are going to design UI for this particular role. By looking at DataConsumer its mostly Read-only on all entity operations. So having this extra policy outside the scope of "DataConsumer" Role is tricky to handle

For me its more of simplicity of Role -> Policies -> Rules to understand and execute on the UX side

**Comment by sureshms** [comment]
This is already supported with new permissions API in #6728.
