### ISSUE TITLE
Adopting `extends` of JSONSchema

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2267]
It would allow us to write safer Java code and define some fields only one time.

- [ ] Check if it is compatible with Python and TypeScript

```java
// Examples of safer Java code.

public abstract class EntityRepository<T extends Entity> {}

private static final Map<String, EntityRepository<? extends Entity>> ENTITY_REPOSITORY_MAP = new HashMap<>();

public static <T extends Entity> void registerEntity(Class<T> clazz, String entity, EntityDAO<T> dao, EntityRepository<T> entityRepository) {}

public static <T extends Entity> EntityReference getEntityReference(T entity) {}

public static <T extends Entity> EntityRepository<T>.EntityHandler h(@NonNull T entity) {}
```

```json
{
  "$id": "https://open-metadata.org/schema/type/entity.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Entity",
  "description": "",
  "type": "object",
  "javaType": "org.openmetadata.catalog.type.Entity",
  "properties": {},
  "required": [],
  "additionalProperties": false
}
```

```json
{
  "$id": "https://open-metadata.org/schema/entity/data/table.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Table",
  "description": "This schema defines the Table entity. A Table organizes data in rows and columns and is defined by a Schema. OpenMetadata does not have a separate abstraction for Schema. Both Table and Schema are captured in this entity.",
  "type": "object",
  "extends": {
    "$ref": "../../type/entity.json"
  },
  "javaType": "org.openmetadata.catalog.entity.data.Table",
  "properties": {}
```
#
https://www.jsonschema2pojo.org/
![image](https://user-images.githubusercontent.com/32617/149961364-1129059a-e777-436a-a8d5-e3abfbda9f4b.png)

@sureshms @harshach @mithmatt @pmbrull

**Comment by pmbrull** [comment]
That would actually be pretty cool. This would allow us to also group a lot of base properties such as `version` or `deleted`. I actually gave it a go and the `pydantic` models are not picking up the inheritance properly though. I am going to ask in https://github.com/koxudaxi/datamodel-code-generator and see if we could potentially do something about it.

Thanks @amiorin

**Comment by mithmatt** [comment]
I recall coming across extends when I was working on policies. 
And then realized that the code generation did not work as expected and dropped the idea. 

Unless we go patch/contribute to the code generation library we use (didn't go with this choice when I stumbled upon this problem)

**Comment by sureshms** [comment]
Inheritance can become an issue a lot of times. Composition is better in a lot of cases. We had all the common fields as the base entity when we started and use composition. But decided to move away from it to flatter the entity structure.

**Comment by amiorin** [comment]
@mithmatt @sureshms are right, `extends` is a no-go. What about `javaIntefaces`.
#
![image](https://user-images.githubusercontent.com/32617/150277739-33a5f1b1-ee91-4c29-bfbb-2d838304eb18.png)

I have used https://jsonnet.org/ in the past to solve the problem of repeating things in JSON/YAML files.

WDYT?

**Comment by mithmatt** [comment]
After giving this some thought, I think we may introduce more challenges if we want the json schema to use javaInterfaces

With Java interfaces, it is possible to make the json schema dependent on standard java interfaces like the ones mentioned above (Serializable, Cloneable, coming from the JDK).

If we are introducing Java interface with the intent to do something (like the following) with custom interfaces, we are likely to introduce more complexity and may break some fundamentals.

```
public class Table implements Versioning {}

public interface Versioning {
   void seUpdatedBy(String updater);
   void seUpdatedAt(long timestamp);
}
```

1. Build complexity - We have to compile the OpenMetadata Java code (to get Versioning interface) before generating the sources (Table entity) and then compile again (for the OM application)
2. We currently follow this neat generation flow: `json-schema --> {java, js, python}`. If we introduce` java --> json-schema --> {java, js, python} `, some of the functionality will obviously not be available in js and python - we benefit in Java, but leave out the others that are critical parts of the OM stack.
3. Additionally, this strategy may be a potential starting point to move away from the schema first principle we have with OM


Due to the above points listed, I'm not in favor of adding javaInterfaces or extends to the schema. 


jsonnet is an interesting tool. However, I think it will introduce similar problem to 2 above
`jsonnet -->  json-schema --> {java, js, python}`

With ~20 or so entities, it does not look worthwhile to introduce jsonnet to reduce repeated items across entity schemas
