### ISSUE TITLE
Collaboration - Activity Threads, Comments, Requests

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2366]
As part of 0.7 we introduced Activity feed based on the change events that are being generated by bot or user activity with-in
OpenMetadata.   Collaboration is one of the founding principles behind the OpenMetadata. 
In 0.9 release we will introduce conversations, threads, referring other users with-in threads and asking questions etc..
Initial thoughts around activity feeds, posts and threads
1. Users should be able to create posts and refer entities and ask questions etc.. 
2. Users should be able to comment on the change log entries. Example User X is edited the description and User Y should be able to reply to the activity thread saying please correct the description. Similarly users can discuss about columns, sample data etc..
3. We should be able to generate a feed per entity. That is group any historic threads per entity. This can later become knowledge threads and users/owners can flag certain threads as important and pin them in the entity page

@sureshms please add more details

## Tasks

- #2645

**Comment by vivekratnavel** [comment]
Initial discussions:

Currently, we are using change descriptions based on events to populate the Activity feed on the homepage. We should start using the `thread_entity` table to persist any activity including the change events. The `thread_entity` table will need schema changes to store `userName`, `createdTimestamp`, `entityType`, etc. 

The [MessageParser](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/MessageParser.java) can be improved to support "#<entityName>" and "@<user/team>" with advanced searches to get nested suggestions such as `<table_name>.<column_name>.<field>`. We can use elastic search to index these entity names and user names.

We should also track `@Mentions` as a separate column in `thread_entity` to be able to display all the relevant threads to a user on the homepage. When a user interacts on a thread by posting a comment, the user should be automatically added to the `@Mentions` column so that they get future notifications of any activity on the thread. We should also support "unsubscribe" feature for users to ignore notifications on a thread. But, it need not be part of this epic. We can add that feature later. Also, we will not support the editing of posts in the initial release.

**User Experience**
Users should be able to start a thread or post comments from two places:
 - Any of the entity pages such as `Messaging Service`, `Table` etc. Users should be able to request a description by clicking the button `Request Description` next to the description field on the page. They should also be able to comment on an existing thread or create a new thread that should automatically be assigned to the owner of the entity. 
 - From the activity feed on the homepage

Activity Feed:
 - It should list all the activity that happens around the entities they follow, by either being the owner of an entity or by participating in any thread.

**Tasks**
- Update "thread_entity" schema to support "userName", "createdTimestamp", "entityType", "followers" etc.
- Add API(s) to serve thread related requests
- Add API to get autosuggestions from elastic search
- UI: Get activity from thread_entity API
- UI: Create mocks to show icons in entity pages to start a thread
- UI: Show autosuggestions for entity names or user/team in posts when "#/@" is used

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya @sanketbambulkar @shahsank3t please take a look at the above details. We need to work on mockups for these.

**Comment by vivekratnavel** [comment]
We have officially merged all the features related to Collaboration that we scoped for this 0.9 release.
