### ISSUE TITLE
Fix sonarqube in maven "Maven session does not declare a top level project"

### ISSUE THREAD

**Issue by asdiamond** [open-metadata/OpenMetadata#2411]
When running `mvn clean install` from the project directory we get: 
```
$ mvn clean install 
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (sonar-verify-execution) on project openmetadata-dist: Maven session does not declare a top level project -> [Help 1]
```

Sonarqube should only be run during CI/CD, so we should reconfigure this so new users don't run into it when getting setup. 

I think we could be hitting this issue: https://stackoverflow.com/questions/18588582/sonarqube-3-7-with-maven-and-jenkins-maven-session-does-not-declare-a-top-leve

@pmbrull Could you help me take a look into this?

**Comment by pmbrull** [comment]
Hi, @asdiamond, thanks for filing this. I'll take a look and see if I can reproduce this locally.
These are my current settings:
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 11.0.12, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

But yes, agree that we can tune this so that it does not run by default locally. Moreover, the actual plugin will fail as it won't find the proper security token. We can add an `activation` key in the pom and only pass that as a parameter during CI
