### ISSUE TITLE
UI: Auth token needs to be renewed instead of logging the user out

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2491]
Currently, Once the user logs-in we get a token from auth provider such as google. UI doesn't renew this token and the session is only valid for an hour. We need to add mechanism to renew the token so the session is valid for longer duration.

**Comment by harshach** [comment]
@vivekratnavel any updates on this?

**Comment by maulikkotak98** [comment]
I can help here with the issue. Please assign this to me.

**Comment by vivekratnavel** [comment]
Hi @maulikkotak98,

Thanks for taking this up. Here are some details on how we can proceed. You can test Okta first and then move on to Google since I have verified that we can get refresh tokens with "offline_scope" in Okta.

This doc should be followed to set up a "SPA application" in Okta to get refresh tokens - https://developer.okta.com/docs/guides/sign-into-spa/react/main/#create-an-okta-app-integration 

Instead of using the oidc-client library which is archived, we should switch to a library like [okta-auth-js](https://github.com/okta/okta-auth-js) that supports [auto-renewal](https://github.com/okta/okta-auth-js#running-as-a-service) of tokens. 

If we set it up correctly, the library itself should take care of renewing tokens before expiry. Please let me know if you need any more details.

**Comment by darth-coder00** [comment]
Reopening as issue still persists for Google and Azure SSO.

**Comment by harshach** [comment]
@vivekratnavel assigning this to you. Lets clean this up and add relevant packages for sign-in

**Comment by chirag-madlani** [comment]
Verified at: https://sandbox-beta.open-metadata.org/my-data
