### ISSUE TITLE
Prematurely bumping up MAJOR VERSION

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2872]
**Affected module**
Backend and UI for Versioning

**Describe the bug**
We are incrementing the MAJOR_VERSION in the following scenario:
- version is  is x.9
- update is MINOR_VERSION update

**To Reproduce**

After 3.9 version, the next version is 4.0

<img width="848" alt="image" src="https://user-images.githubusercontent.com/5906984/154829052-118482bd-c220-4da2-a5ff-3336092a73c4.png">

**Expected behavior**
Ideally 3.10 should come in after 3.9 if the update is a MINOR VERSION update
We should not bump up MAJOR VERSION when MINOR_VERSION becomes 10 

**Version:**
 - OpenMetadata version: main branch hash 28807f8c

**Additional context**

**Comment by harshach** [comment]
@mithmatt for simplicity we kept the major version as current_version - prev_version  == 1.0 . So 3.9 going to 4.0 is not a major version its just 0.1 increment from previous version. We may need to re-look at the whole thing but just making it 3.10 doesn't make sense in this context. Since the major_version update will make it 4.10 not 4.0. So lot of edge cases, the current expectation of "current_version - prev_version  == 1.0" keeps a sanity check.

**Comment by mithmatt** [comment]
Thanks for the context @harshach 

I was under the impression that MAJOR_VERSION update is considered as a breaking change 


I was expecting 3.9 --> 3.10 for MINOR_VERSION update patch
and 3.10 --> 4.0 for MAJOR_VERSION update patch

**Comment by harshach** [comment]
ya we went back'n forth on this. Ideally it makes sense to have major number increment only for the major version changes instead of continuous increment like it happens i.e. 0.9->1.0, 1.1 etc..  this means several updates at descriptions or tags can continue to update the version from 0.1 -> 0.99 . It also depends on how we interpret the version value itself is it a double or a version string like semantic version . Currently version is double and adding 0.1 for every increment it will come to 1.0 from 0.9. 
We need to covert that into a string and make it follow https://semver.org to version for minor and major. IMO this is ideal from what we have right now. 

Given data entities such as tables does go through a release example recently there was an ask if one could align the versioning to their own release of tables , i.e new feature added to a table(a new column to support a query , dashboard etc..) so converting this to semantic versioning may make sense vs what we have right now. Atleast it will be easy to under what is major vs minor update by looking at the version number.

@sureshms thoughts?

**Comment by mithmatt** [comment]
Upvote for semver -- since that is an industry standard everyone is used to.

**Comment by sureshms** [comment]
Resolving this as won't fix.
