### ISSUE TITLE
Access Control by Team instead of Role

### ISSUE THREAD

**Issue by flowy0** [open-metadata/OpenMetadata#2907]
**Is your feature request related to a problem? Please describe.**
At the moment, access control is only granted by role. 
I would like to request a more granular access control for the data that can be controlled by teams.
Given that we could tag a database/dataset to a Team, it would be ideal if only those team members can see the metadata/sample data.

This would be very useful in organisations where data is very sensitive and data governance is important to them.

**Describe the solution you'd like**
Datasets are tagged to Teams, and only users within authorised teams should be allowed to view metadata and sample data/

Eg: 
Database1 is owned by Team1, only users in Team1 should be allowed access to this set of metadata and sample data
Database2 is owned by Team2, only users in Team2 should be allowed access to this set of metadata and sample data

**Describe alternatives you've considered**
If there are ways to use/modify the role instead, perhaps that can be an alternative method.

**Additional context**
If we could integrate an external database that references which user belongs to which team, if we could link that to the OpenMetadata Users/Teams, that would be fantastic.

At the moment, we have a Postgresql database containing the users in each team.

**Comment by cometta** [comment]
add extra info from discussion over slack 
commented by @mithmatt 

I haven't thought through all the specifics yet. But here is what I've thought through so far:
We use attributes of the user as part of the role. Currently we have userRole attribute. We will need to look into supporting userTeam attribute - so team1 can be specified
Restricting access to specific tables - currently we have entityType and entityTags to group what entities we can restrict access to (these remain unused in our 0.8 release implementation). We will have to extend this to support entityFqnPrefix or so so that we can specify "database1.*"
We'll have to add a new Operation that indicates the behavior -- ViewMetadata or ViewProfilerData
Combination of above 3 needs to be built into a seamless UI experience (adding permission and allowing view based on policy evaluation)

**Comment by mithmatt** [comment]
Tasks

- [ ] #3029
- [ ] #3031 
- [ ] #3032 
- [ ] #3033

**Comment by mithmatt** [comment]
UX note: The table will be still search-able but going to the table specific page will yield some message like "No permission -- reach out to table owner", if the user does not have ViewMetadata permission

**Comment by mithmatt** [comment]
Backend code for this is ready in https://github.com/open-metadata/OpenMetadata/pull/3034
Waiting until after 0.9 release for merging this change to aim for 0.10 release

**Comment by flowy0** [comment]
@mithmatt Tried to test this feature based on your fork, but not sure whether I set this up correctly. I was still able to view tables belonging to other teams.

**Comment by sureshms** [comment]
This is addressed by #6860. Marking this as resolved.
