### ISSUE TITLE
mvn -DskipTests should skip UI tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3016]
**Is your feature request related to a problem? Please describe.**
When spinning up the docker containers locally or during the CI, we run `sh docker/run_local_docker.sh`, which executes `mvn -DskipTests clean package`. This starts the building process of the OM server container without running backend tests, but still I believe there are selenium tests running, as I can see outputs as

```
PASS @openmetadata src/components/common/error-with-placeholder/ErrorPlaceHolder.test.tsx
```

**Describe the solution you'd like**
Is there a way we can make sure that we are able to skip them too? That could save a few minutes on unnecessary testing.

**Describe alternatives you've considered**

**Additional context**

**Comment by pmbrull** [comment]
cc @mithmatt maybe you can chip in here. Thanks!

**Comment by mithmatt** [comment]
```
[INFO] --- frontend-maven-plugin:1.11.0:yarn (yarn run build-check) @ openmetadata-ui ---
[INFO] Running 'yarn run build-check' in /Users/matt/Documents/projects/open-metadata/OpenMetadata/openmetadata-ui/src/main/resources/ui
[INFO] yarn run v1.22.17
[INFO] $ yarn run lint && yarn run test
[INFO] $ eslint "./src/**/*.{js,jsx,ts,tsx}"
[INFO] $ jest --passWithNoTests
```

Tests are being run  during package because of this line:

https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/pom.xml#L127-L137
which says `yarn run build-check`

which is configured here
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/package.json#L86

to run `yarn run lint && yarn run test` 

if we change the package.json script to honor the argument -DskipTests in some form, we should be able to avoid running the UI tests during package

**Comment by pmbrull** [comment]
Thanks for chipping in @mithmatt 🙏
