### ISSUE TITLE
Feedback on 0.9 release UI (look and feel/cosmetic issues)

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#3115]
Let's collect all the feedback related to 0.9 here:

- [x] Add hover over on the user icon and show user name and details. See GitHub as an example:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/1417689/156616144-e83598cc-9a20-496e-bb26-9f2036afbb65.png">

- [x] Can we have a little more saturation/vibrant colors for user icons/profiles? They look very dull.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1417689/156616589-a9dd47f9-4d4f-42fe-979f-2eb55ce3d9da.png">

- [x] Have consistent user naming. For example name used as post header is different from name that appears in mention:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1417689/156617111-ab07ef5d-f2af-4de3-956e-718e68bf50f0.png">

- [x] The paper plane icon could lose the grey box around and just have a grey and purple version (when sending). It could be smaller and subtler.

<img width="89" alt="image" src="https://user-images.githubusercontent.com/1417689/156620762-53bb9390-446b-499f-8db8-b2e56de39c00.png">

- [x]  Make entire User card clickable to get user details in Users page. Right now click is allowed only on the name.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1417689/156624338-bbe275be-b8f0-4d6b-80fd-86e4473212cd.png">

- [x] Two ingestion bots appear in Users page

<img width="777" alt="image" src="https://user-images.githubusercontent.com/1417689/156624771-4ab2dacc-2c35-48fb-94d7-bd9689e3aed0.png">

- [x] Updated `Configure Webhook` documentation

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1417689/156625076-f98546fb-bfbc-4aaf-bacf-9914cc3c059f.png">

- [x] URL validation for webhooks may be incorrect. For example: http://localhost or http://<IP address> throws validation error:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/1417689/156626701-95ca73e5-8838-40da-bc8f-216a01540135.png">

- [x] On the webhook listing page, the filters on the left column are not operational
- [x] Change the following text:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/1417689/156630901-fdbe088d-47f3-4812-8bf2-45264ef2c6cb.png">
to
**Webhook allows external services to subscribe to the metadata change events. When the event you subscribed for happens, an HTTP POST request is sent to the callback URL provided with the event details. Learn more about the feature in our Webhooks Guide.**

- [x] Recently search includes some weird strings zzz, zzzz, zzzzd
<img width="300" alt="IMG_6929" src="https://user-images.githubusercontent.com/1417689/156632134-56f6c745-613b-4d18-a622-2018959d6138.png">

- [x] User search may not be working under Users tab. For example when I search for my name, this is what I see.  But Search works fine in Admin tab. Users list should be a superset that should include, Users, Admins, and Bots.
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1417689/156638872-91720e75-6784-42fc-997e-6701cc1e9864.png">

- [x] Queries are shown in a very long box. Perhaps this should be similarly sized as activity feed boxes. Also user name (Last run by xxx) shown in a different format compared to posts. We need to decide on what to show for user names across all the pages.
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/1417689/156641070-f67409db-fb02-4a12-a599-6684967273d4.png">

**Comment by harshach** [comment]
- [ ] If a entity already exists in recently viewed , do not add that entity again . Example "shopify" appearing multiple times
<img width="299" alt="image" src="https://user-images.githubusercontent.com/38649/156635091-f8a1cfc1-3c92-487d-8c05-1fab816ed41a.png">
also it looks like we are adding the database name in the list instead of entity_name

**Comment by sureshms** [comment]
- [ ] Need a profile picture for ingestion bot

**Comment by vivekratnavel** [comment]
- [ ] All the active tabs should have a consistent background color (today, some tabs have a grey background vs white)
- [ ] There should be a clear separation between the sidebar and the main content space across all the pages and it should not depend on whether there is more data or less data on the sidebar or the main content space.
- [ ] Change text: "No description added" -> "No description", "No rules added" -> "No rules" etc.
- [ ] Spacing needs to be consistent across all the pages. We should define spacing between the Title text, description and tab content 

<img width="1145" alt="Screen Shot 2022-02-28 at 10 55 43 AM" src="https://user-images.githubusercontent.com/1051198/156041904-5c380be6-fa14-4049-9e2c-0af15e6b7a09.png">

- [ ] Fix the spacing in these cards

<img width="1199" alt="Screen Shot 2022-02-28 at 10 59 02 AM" src="https://user-images.githubusercontent.com/1051198/156042441-2b9137bc-8e9f-416d-8e1f-c7115fb0fe11.png">

- [ ] Fix this

<img width="283" alt="Screen Shot 2022-02-28 at 11 00 35 AM" src="https://user-images.githubusercontent.com/1051198/156042589-2b0f3e2f-f02e-4321-81c0-d0d6333b39d6.png">

- [ ] There should be a link in the user dropdown menu to go to the "Activity Feeds" page. 
- [ ] Searching in the "Users" page does not search "Admins" or "Bots". 
- [ ] The user card in the "Users" page should display the team names instead of just count 
- [ ] Replace "Click here" links with a button
- [ ] Clean user click for non-admin https://github.com/open-metadata/OpenMetadata/issues/3110
- [ ] https://github.com/open-metadata/OpenMetadata/issues/3120

**Comment by harshach** [comment]
- [ ] For dashboards in recently viewed we are showing the id of a dashboard 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/38649/156659469-e74c36ee-6f25-4cc7-8cec-4f500ba8d4cf.png">
For future references, Dashboard names are not unique unlike tables or topics hence we register the id (which can be numerical) so instead of showing id lets depend on displayName

**Comment by harshach** [comment]
[]  we shouldn't show the "Reply in conversation" instead it show the no.of replies. As we already have "Reply button below the thread
<img width="882" alt="image" src="https://user-images.githubusercontent.com/38649/156947869-d73169ab-a59d-40a1-86b5-1c2cf48f3181.png">

**Comment by harshach** [comment]
[] given the settings menu has grown quite a bit for the Admins, lets order them in alphabetical order 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/38649/156981399-d1facd61-17e8-46aa-9cf8-09e6ceac75f1.png">

**Comment by darth-coder00** [comment]
> * [ ]  For dashboards in recently viewed we are showing the id of a dashboard
> 
> <img alt="image" width="251" src="https://user-images.githubusercontent.com/38649/156659469-e74c36ee-6f25-4cc7-8cec-4f500ba8d4cf.png">
> 
> For future references, Dashboard names are not unique unlike tables or topics hence we register the id (which can be numerical) so instead of showing id lets depend on displayName

UI takes displayName for recently viewed section, if displayName is not present, we show name(numeric-id) we get from results

**Comment by vivekratnavel** [comment]
> > > * [ ]    For dashboards in recently viewed we are showing the id of a dashboard
> > > 
> > > <img alt="image" width="251" src="https://user-images.githubusercontent.com/38649/156659469-e74c36ee-6f25-4cc7-8cec-4f500ba8d4cf.png">
> > > For future references, Dashboard names are not unique unlike tables or topics hence we register the id (which can be numerical) so instead of showing id lets depend on displayName
> > 
> > 
> > UI takes displayName for recently viewed section, if displayName is not present, we show name(numeric-id) we get from results
> 
> this is not reproducible

When I tried to assign owner, I was getting this in my activity feed, so we will need to fix this.
<img width="828" alt="Screen Shot 2022-03-09 at 12 16 12 AM" src="https://user-images.githubusercontent.com/1051198/157400425-25e4c44e-7ec6-4b22-9c72-4690ba60a562.png">

**Comment by Sachin-chaurasiya** [comment]
> > > > * [ ]     For dashboards in recently viewed we are showing the id of a dashboard
> > > > 
> > > > <img alt="image" width="251" src="https://user-images.githubusercontent.com/38649/156659469-e74c36ee-6f25-4cc7-8cec-4f500ba8d4cf.png">
> > > > For future references, Dashboard names are not unique unlike tables or topics hence we register the id (which can be numerical) so instead of showing id lets depend on displayName
> > > 
> > > 
> > > UI takes displayName for recently viewed section, if displayName is not present, we show name(numeric-id) we get from results
> > 
> > 
> > this is not reproducible
> 
> When I tried to assign owner, I was getting this in my activity feed, so we will need to fix this. <img alt="Screen Shot 2022-03-09 at 12 16 12 AM" width="828" src="https://user-images.githubusercontent.com/1051198/157400425-25e4c44e-7ec6-4b22-9c72-4690ba60a562.png">

@vivekratnavel, for feed we get  `about: <#E/dashboard/sample_superset.10/owner>` and there fqn is `sample_superset.10`, so we take the name from fqn and show it in the UI.

**Comment by Sachin-chaurasiya** [comment]
The icon is not aligned with the left margin in service pages.

<img width="442" alt="Screen Shot 2022-03-15 at 10 57 23 PM" src="https://user-images.githubusercontent.com/1051198/158525994-a1162321-da5b-4832-a212-5d7373188da5.png">


Misaligned tag icon in all the entities pages except tables.

<img width="607" alt="Screen Shot 2022-03-15 at 12 59 09 PM" src="https://user-images.githubusercontent.com/1051198/158461098-d82b90a5-cd09-4dea-ae16-5811b6c5a737.png">

Misaligned icon:

<img width="280" alt="Screenshot 2022-03-15 at 5 21 30 PM" src="https://user-images.githubusercontent.com/83201188/158372350-2b2ee652-9dee-42a7-a7fd-fc6f54ff7a05.png">

Tag details UI changes after adding a new tag category 
![image](https://user-images.githubusercontent.com/67048554/157644486-7ad2ea15-1890-4c72-bfcf-16f662f5e7b8.png)

**Comment by parthp2107** [comment]
Link pop-up getting overlapped.

<img width="744" alt="Screenshot 2022-03-22 at 11 11 28 AM" src="https://user-images.githubusercontent.com/83201188/159415712-61f80c0e-cd98-4cc7-bd6c-d6a7cc86a830.png">

**Comment by vivekratnavel** [comment]
Icons are misaligned. I was using latest Firefox on Mac OS. 

<img width="510" alt="Screen Shot 2022-03-22 at 2 57 06 AM" src="https://user-images.githubusercontent.com/1051198/159454982-0012bcf0-5ecb-4880-b64e-839b00a0202a.png">

**Comment by darth-coder00** [comment]
Segregated remaining things to different tasks
- #3760
- #3761
- #3762 
- #2783

Closing this ticket
