### ISSUE TITLE
Fix linting in ingestion/source

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3397]
Fix linting issues in ingestion/source

**Comment by ulixius9** [comment]
Closing this issue as fixed with following prs
- https://github.com/open-metadata/OpenMetadata/pull/8034
- https://github.com/open-metadata/OpenMetadata/pull/8018
- https://github.com/open-metadata/OpenMetadata/pull/8008
- https://github.com/open-metadata/OpenMetadata/pull/8002
- https://github.com/open-metadata/OpenMetadata/pull/7987
