### ISSUE TITLE
Ingestion: Snowflake Usage is running into issues during Lineage extraction

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3527]
**Affected module**
ingestion

**Describe the bug**
<img width="993" alt="image" src="https://user-images.githubusercontent.com/38649/159100087-bd3b37a8-0abd-4b52-b8c7-dd0e2939e3b3.png">

Reported by @kevinbtai

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ulixius9** [comment]
Hey @harshach
This error was because in snowflake some query returns the result set from table function instead of using an actual table, for example: [query](https://github.com/open-metadata/OpenMetadata/blob/1d7d38aa73baae1bd60b354f3a93c61d9d603120/ingestion/src/metadata/utils/sql_queries.py#L137) which we are using to fetch query_history for snowflake usage.The lineage runner fails to parse such queries. 

This error was handled with PR #3434.

**Comment by harshach** [comment]
@ulixius9 @ayush-shah to double-check lineage extraction across DBS and schemas as well. Make sure if the query only contains the "schema.table_name" vs "db.schema.table_name"

**Comment by ayush-shah** [comment]
This is fixed as per the results in recent testing.
