### ISSUE TITLE
Document Redshift SSL

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4374]
connect_args={'sslmode': 'prefer'} or verify-ca , verify-full

User can send this through connect args . But thiught we should capture as additional param and add to connect args

**Comment by harshach** [comment]
If the parameter sslmode is set to verify-ca, redshift connector will verify that the server is trustworthy by checking the certificate chain up to a trusted certificate authority (CA). 
If sslmode is set to verify-full, redshift-connector will also verify that the server host name matches its certificate. The SSL connection will fail if the server certificate cannot be verified. verify-full is recommended in most security-sensitive environments.

In verify-full mode, the cn (Common Name) attribute of the certificate is matched against the host name. If the cn attribute starts with an asterisk (*), it will be treated as a wildcard, and will match all characters except a dot (.). This means the certificate will not match subdomains. If the connection is made using an IP address instead of a host name, the IP address will be matched (without doing any DNS lookups).

 if a root CA file exists, the behavior of sslmode=require will be the same as that of verify-ca, meaning the server certificate is validated against the CA. Relying on this behavior is discouraged, and applications that need certificate validation should always use verify-ca or verify-full


Lets document this in a section of redshift cc @ShilpaVernekar

**Comment by pmbrull** [comment]
cc @codingwithabhi, please add this when working on the redshift docs 🙏
