### ISSUE TITLE
UI: Explore page improvements

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4556]
Improve the font-sizes and profile picture size of the owner and improve spacing for better UX.

@devyani-kaushik  to provide mocks

**Comment by devyani-kaushik** [comment]
<img width="819" alt="Screenshot 2022-05-03 at 10 41 56 AM" src="https://user-images.githubusercontent.com/103238069/166407126-397bf7ff-5707-4171-baac-b567a6267866.png">

**Comment by vivekratnavel** [comment]
@devyani-kaushik Thank you for posting the mock. The placeholder profile picture("S") looks good when there is no real profile picture. Will it look good or make sense to display the real profile pictures at this size?

**Comment by devyani-kaushik** [comment]
So on this page, our priority is the entity, which is why we have given a smaller size to the user profile. And as per the priority, it shouldn't be an issue if the image is small

<img width="893" alt="Screenshot 2022-05-03 at 1 26 45 PM" src="https://user-images.githubusercontent.com/103238069/166420725-8f357220-3e2f-4f7b-bcb1-ec272f8c0095.png">
