### ISSUE TITLE
Configure ODBC drivers / libraries in the ingestion container

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#4839]
Mssql & Azuresql uses pyodbc package, but it needs odbc drivers to be configured or else it returns failure

**Comment by pmbrull** [comment]
from slack:

```
We tried to add dependency of Oracle and SQL Server to Ingestion docker image. However, this cannot be done due to a primary reason that both [Oracle](https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc) and [MS SQL Server Drivers](https://github.com/MicrosoftDocs/sql-docs/issues/6494#issuecomment-905434817) don't support Mac M1 Chip.
```

**Comment by pmbrull** [comment]
Oracle has been fixed already

**Comment by pmbrull** [comment]
In this same piece of work we should also make sure that we can ship the `db2` plugin that right now has issues building on M1 https://github.com/ibmdb/python-ibmdb#pre-requisites

**Comment by harshach** [comment]
@akash-jain-10 what is remaining here?

**Comment by pmbrull** [comment]
@harshach just tried to run the `db2` plugin installation with their latest version `0.3.8` and still getting an arch error on M1. Same error as discussed here https://github.com/ibmdb/python-ibmdb/issues/708

What we're currently doing is not adding db2 by default when installing `all`. We can update this after the lib has updated their builds.

@akash-jain-10 not sure if there's any way to ship this package on our images without getting into this issue. Otherwise users might need to install `db2` inside the containers if needed

**Comment by harshach** [comment]
@akash-jain-10 any reason we want to make this M1 dependent only? At worst, we can have multiple archs right. This really affects the users right now. I have seen this question pop up multiple times. Anyone who is doing a POC is doing it on Linux and not M1. We are essentially handicapping ourselves by trying to go for single arch images

**Comment by akash-jain-10** [comment]
Hello @harshach . Closing this ticket as we have covered Oracle and MSSQL Database drivers within the Ingestion container. Will be creating a new one for ibmdb and track it there as we would be waiting for ibm community to provide drivers for arm-64 architecture.
