### ISSUE TITLE
Not able to register in the Slack community

### ISSUE THREAD

**Issue by francescomucio** [open-metadata/OpenMetadata#559]
I tried with my personal email address and my gmail one, in both cases I get the suggestion to use my work email.

As a freelancer, these are mostly my work related email accounts :)

![image](https://user-images.githubusercontent.com/3058143/134183000-7d012008-6071-4a91-8d49-e032a006458f.png)

**Comment by ksivam** [comment]
I got the same error yesterday when I tried to join the slack channel. 

It happened when I entered my personal gmail/password in the textbox manually, instead of Google OAuth sign-in.  

Think I tried opening the link in incognito mode, and was able to get the sign-in with Google option and used my personal gmail - which ultimately worked.

Not sure what the exact problem is, but try incognito or signing out of slack, to get the sign-in with Google/3rd part Oauth service option.

**Comment by francescomucio** [comment]
thank you for the suggestion @ksivam, unfortunately I tried but this didn't work for me

**Comment by harshach** [comment]
@francescomucio we are looking into this. You should be able to join with your personal email id as well.

**Comment by harshach** [comment]
@francescomucio did you try with you generic google id or your work's email (could be google). I've tried with few accounts and different community slack channel. It looks like slack is only allowing us to join if you use an email id with "@gmail.com" instead of work account domain . Please let us know if you tried with "@gmail.com" email and still running into issues

**Comment by harshach** [comment]
@francescomucio checking to see if you got a chance to try it out again with your gmail.com email id. Please do let us know. Thanks

**Comment by francescomucio** [comment]
still the same error, I tried with my gmail and my personal domain account. Could you try to send an invite to francescomucio@gmail.com?

**Comment by harshach** [comment]
@francescomucio adding you to the channel. Here is another link to try. https://openmetadata.slack.com/join/shared_invite/zt-wksh1bww-iQGk45NTw6Tp4Q9UZd6QOw#/shared-invite/email

**Comment by francescomucio** [comment]
This worked :)

**Comment by harshach** [comment]
Thanks @francescomucio for finding this issue. We fixed it now interested members can use the https://slack.open-metadata.org
