### ISSUE TITLE
Provide meaningful errors on Airflow APIs

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#5835]
**Affected module**
Ingestion, Airflow

**Describe the bug**
Currently, we are returning full stack traces of errors when deployment does't work.
We should capture these full stack traces and provide meaningful errors
Errors like these are not helpful for our end users
![image](https://user-images.githubusercontent.com/38649/177200213-ebc337fb-1bdc-4cbc-b3ed-3fb1c8f7673d.png)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
We need to:
- follow the flow of the code when the dag gets built
- validate the different points where we can get an exception
- make sure that explicit exceptions are being thrown
- capture those exceptions at the root and send comprehensive error messages back to the users

The logic is already different in main, but for example in `0.11.x` a couple of errors can happen:
1. we have an error retrieving the service, and yet we throw a "verify your config is correct" when the problem is in the communication between Airflow and OM
2. we have an error retrieving the token in the ometa_api. We still throw the "verify your config is correct" instead of explaining what is going on.

Double-check all these cases and return proper error messages
