### ISSUE TITLE
feature: allow configuration of dbt s3 from the UI without AWS credentials

### ISSUE THREAD

**Issue by psg2** [open-metadata/OpenMetadata#6291]
**Is your feature request related to a problem? Please describe.**

Allow the user to configure from the UI dbt from s3 without credentials to default for boto3 credentials resolution so users are able to configure other methods such as IAM roles

**Describe the solution you'd like**

Remove the required attributes from AWS Acess Key ID and AWS Secret Access Key in the UI to start, but we could also add some tooltips to let the users know what will the fallback be sending boto3 [docs page](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials) maybe

**Describe alternatives you've considered**

None so far

**Additional context**

Slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1658520119462499

**Comment by Beetelbrox** [comment]
Hai I created an [effectively identical request](https://github.com/open-metadata/OpenMetadata/issues/6213) a couple of days ago, shall I close that one and we track the request on this ticket? Thanks!

**Comment by pmbrull** [comment]
oooh so sorry @Beetelbrox, missed your FR. Just closed that. We can keep the convo here. I'll get in touch with the team so that we can get this fixed asap :)

Thank you both for the amazing help

**Comment by pmbrull** [comment]
@ShaileshParmar11, from Slack (Thanks @psg2), the issue seems to be here:

[https://github.com/open-metadata/OpenMetadata/blob/ba94121fced8ce1122fe0e0c2e4f408[…]s/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx](https://github.com/open-metadata/OpenMetadata/blob/ba94121fced8ce1122fe0e0c2e4f408eba7ba60b/openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx#L95)
[https://github.com/open-metadata/OpenMetadata/blob/ba94121fced8ce1122fe0e0c2e4f408[…]s/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx](https://github.com/open-metadata/OpenMetadata/blob/ba94121fced8ce1122fe0e0c2e4f408eba7ba60b/openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx#L115)
