### ISSUE TITLE
 Remove unnecessary docker-compose files for starting only DBs and Elasticsearch

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7099]
**Issue**
We have redundant docker-compose files for starting only DBs and Elasticsearch (`docker-compose-dev.yml` and `docker-compose-dev-postgres.yml`), which we must maintain. These files are not used anywhere except in one part of the documentation [here](https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests/openmetadata-server). 

The possible solution to remove them is to start using `docker-compose.yml` instead of `docker-compose-dev.yml`.

**Comment by akash-jain-10** [comment]
Moving this for 0.13 Release.

**Comment by TheGor1lla** [comment]
What would be the way with handling the different configurations of dev/prod here?
Unsure if docker-compose profiles can handle networks, but it might be worth a try

**Comment by RahulSurwade08** [comment]
Hey, I would love to work on this issue under hacktoberfest. How can I get started?

**Comment by akash-jain-10** [comment]
Hey @RahulSurwade08. Thanks .

The requirement for the issue here is -

- [ ] We will need to remove the [docker-compose-dev.yml](https://github.com/open-metadata/OpenMetadata/blob/main/docker/local-metadata/docker-compose-dev.yml) and [docker-compose-dev-postgres.yml](https://github.com/open-metadata/OpenMetadata/blob/main/docker/local-metadata/docker-compose-dev-postgres.yml) files.
- [ ] Update Docs [here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-docs/content/developers/contribute/build-code-and-run-tests/openmetadata-server.md#prerequisites) to use the command `docker-compose -f docker/local-metadata/docker-compose.yml -d up mysql elasticsearch`
- [ ] Add another command in the docs [here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-docs/content/developers/contribute/build-code-and-run-tests/openmetadata-server.md#prerequisites) to use the command for postgresql as DB `docker-compose -f docker/local-metadata/docker-compose-postgres.yml -d up postgresql elasticsearch`

Content for third task -

> - For an easy install of PostgreSQL and ES, just install Docker on your local machine and run the following commands from the top-level directory
> `docker-compose -f docker/local-metadata/docker-compose-postgres.yml -d up postgresql elasticsearch`

Let us know if you have any further questions / queries !
