### ISSUE TITLE
new user signup throws EntityNotFound error

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7174]
**Affected module**
UI

**Describe the bug**
During signup page, we are looking up the username and throwing entitynotfound error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/188202125-951525bb-b3fb-4e9c-bce8-099327010ace.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by vivekratnavel** [comment]
@chirag-madlani After signin, the first call we used to make was `/api/v1/users/loggedInUser?fields=profile,teams,roles`. If it throws an EntityNotFoundException, we ignore that (not show toast error) and show the first-time Signup page for the user to pick the teams they want to join. 

Now we are also hitting the permissions API which throws an error since the user is not found in the database and this is shown in the toast message.

<img width="1728" alt="Screen Shot 2022-09-02 at 11 38 09 AM" src="https://user-images.githubusercontent.com/1051198/188217619-51d9d4a5-fd78-4428-882e-ea475c5f193d.png">
