### ISSUE TITLE
Review ingestion integration tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#798]
Running the local Docker Compose and `local_ingestion_dependency.sh` does not seem to be enough to get up and running with the [Integration Tests](https://docs.open-metadata.org/open-source-community/developer/run-integration-tests).

With the docs approach, we get the following failures:

```
FAILED tests/integration/hive/test_hive_crud.py::test_check_table - TypeError: __init__() takes 2 positional arguments but 4 were given
FAILED tests/integration/ldap/test_ldap_crud.py::test_read_user - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8585/api/v1/users/name/john_doe
FAILED tests/integration/mysql/test_mysql_crud.py::test_read_schema - sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
FAILED tests/unit/helpers_test.py::RestTest::test_5_create_table - requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8585/api/v1/databases?fields=service
FAILED tests/unit/workflow_test.py::WorkflowTest::test_execute_200 - TypeError: not all arguments converted during string formatting
```

and a bunch of tests not passing.

Ideally, the tests should run correctly out of the box to help us validate new contributions. If needed, we should update the docs as well to ease and incentivize new developments.

Thanks!

**Comment by vijaypm** [comment]
In case anyone else is looking at this issue, I was able to make test_mysql_crud.py work with a few minor changes to the test case. Please see the attached git diff patch file. 
[ISSUE-798_mysql.patch.txt](https://github.com/open-metadata/OpenMetadata/files/7369570/ISSUE-798_mysql.patch.txt)
Please note that for this patch to work, you will need to follow these instructions:
1. Checkout tag 0.4.0
2. Update docker/metadata/docker-compose.yml as indicated in the patch file.
3. Bring up OpenMetadata services with (remember to configure Docker to allocate at least 4GB memory otherwise ElasticSearch will keep crashing)
> docker-compose up
4. Install python packages
> pip install -r ingestion/requirements.txt
> pip install -e ingestion
> pip install pytest
> pip install pytest-docker
5. Update ingestion/tests/integration/mysql/test_mysql_crud.py as indicated in the patch file
6. Run integration test
> cd ingestion/tests/integration/mysql/
> pytest -s -c /dev/null

**Comment by vijaypm** [comment]
MySQL tests were fixed as part of [PR #914 ](https://github.com/open-metadata/OpenMetadata/pull/914/)

**Comment by vijaypm** [comment]
Hive tests being fixed as part of PR #988

**Comment by vijaypm** [comment]
Ldap test has been fixed as part of PR #1088

**Comment by vijaypm** [comment]
Split the issue with failing unittest into issue #1091

**Comment by vijaypm** [comment]
@pmbrull I believe this issue can be closed. PTAL.

**Comment by pmbrull** [comment]
Hi, @vijaypm!!

Amazing work on this, thanks a lot for tackling the tests. It will be much safer now to make evolutions to the code 🙏 

We can close this 🤗  Feel free to open further issues if needed!
