### ISSUE TITLE
Hyperlink modifications on Profiler Workflow

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#8407]
Modifying the links in the UI as the current link in the profiler workflow is broken

![image](https://user-images.githubusercontent.com/40225091/198509578-7d8b6e2d-e76c-4b43-867b-ba963afc2f1b.png)
![image](https://user-images.githubusercontent.com/40225091/198509586-6772a71a-69de-4ae3-bd75-24b349d5ced1.png)

The link takes the user to https://docs.open-metadata.org/openmetadata/ingestion/workflows/profiler

New Link: https://docs.open-metadata.org/connectors/ingestion/workflows/profiler

**Comment by inspire99** [comment]
@ayush-shah , could you check if this issue can be closed ? Since https://github.com/open-metadata/OpenMetadata/pull/7999 fixes this and related issue - https://github.com/open-metadata/OpenMetadata/issues/7996.

I also checked the git log history of docs.constants.ts under openmetadata-ui.

The link is corrected as follows:

export const WORKFLOWS_PROFILER_DOCS =
  'https://docs.open-metadata.org/connectors/ingestion/workflows/profiler';

**Comment by Sachin-chaurasiya** [comment]
Closing this as it's already fixed.
