### ISSUE TITLE
Preprare 0.12 to 0.13 upgrade docs

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8501]
**Is some content missing, wrong or not clear?**
Preprare 0.12 to 0.13 upgrade docs

**Comment by alancmag** [comment]
### Examples of a mininal and complete production-ready docker-compose files on the Docker Deployment section.
An example of MySql and Postgres compose files, with Volume examples included, and with comments if possible. This will help a lot.

**Comment by alancmag** [comment]
### Improve the docs about Security

The *Docker Deployment -> Enable Security* [section](https://docs.open-metadata.org/deployment/docker/security) is empty, it should be more detailed because it leaves the impression that there is no security, but Basic Auth is enabled by default.

The Deployment -> Enable Security [section](docs.open-metadata.org/deployment/security#enable-security) does not metion that Basic Auth is enabled by defalt. It could be more detailed about how it comes out of the box, and that there are other *options* because the way that it is, it gives the impression that you *must* use other Auth solution.

**Comment by alancmag** [comment]
### Move the Backup and Restore section to a Top level Section

The Backup/Restore section is almost 'hiden' inside the [Upgrade OpenMetadata section](https://docs.open-metadata.org/deployment/upgrade/backup-metadata).
I think that this section deserves to be more prominent (have its own section maybe?) since its a vital part of a production enviroment.

**Comment by pmbrull** [comment]
@ulixius9 anything pending here?

**Comment by ulixius9** [comment]
Nope
