### ISSUE TITLE
Mask sensitive info from API responses

### ISSUE THREAD

**Issue by najdalq** [open-metadata/OpenMetadata#8648]
**Affected module**
Does it impact the UI, backend, or Ingestion Framework?
backend 

**Describe the bug**
I’ve just Connected the OM with Public Postgres DB and then go to inspect the end user can see the password of this DB which is a big security bug. 

Screenshots or steps to reproduce
![Screenshot from 2022-11-10 15-54-21](https://user-images.githubusercontent.com/90555025/201100388-3ad432c3-2bd0-4e4b-9ad2-4c23499a678a.png)

**Expected behavior**
The end user can see the password of the database 
**Version:**
 - OS: Ubuntu 20.04.5
 - Python version: 3.8.10
 - OpenMetadata version: 0.12.2

**Comment by pmbrull** [comment]
@nahuelverdugo do you want to chip in here? 🙏

**Comment by nahuelverdugo** [comment]
Hi @najdalq,
Currently, the passwords are only sent to the admins/bots, so any other user or unauthenticated one cannot see them (in DB, all these values are encrypted).
We also support the configuration of a Secrets Manager, where we can use secret ids stored in AWS Secrets Manager or AWS Parameter Store for the passwords that add another layer of security.
To start working on this issue and to understand the expected behavior, I would like to ask how you think it should work. Should we send all of them masked with asterisks? Only allow the admins to edit them? 

Thank you!

**Comment by sureshms** [comment]
@nahuelverdugo we should only send the password to the ingestion framework and probably never to the UI. cc @harshach thoughts?

**Comment by harshach** [comment]
@sureshms yes that's what we were discussing yesterday with @nahuelverdugo always send masked passwords except for ingestion-bot
