### ISSUE TITLE
UI: Lineage is not working properly for 1000+ nodes, performance issue

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#8795]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/202120509-5e948e60-b346-4352-bcee-98d536a3d5e0.png">

**Comment by parthasarathy93** [comment]
Hi @ShaileshParmar11  any updates on this issue

**Comment by sureshms** [comment]
- [ ] Instead of showing 3 upstream and 3 downstream lineage nodes by default, show 1 upstream and 1 downstream. Add ability to expand the upstream/downstream nodes one at a time. Expanded nodes should also allow shrinking.
- [ ] Support for showing a large number of lineage nodes. (This requires more thinking).
