### ISSUE TITLE
UI: Optimize the backend calls

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#9092]
**Affected module**
UI

**Describe the bug**
We are making unnecessary and sometimes duplicated calls. This ticket is to track and resolve those.

### Landing page
1. Users
We are making 2 calls one to fetch follows, owns and another one profile
- https://sandbox.open-metadata.org/api/v1/users/0cd4048d-ce07-4699-a86f-98ac45dbdb4d?fields=follows,owns
- https://sandbox.open-metadata.org/api/v1/users/name/harsha?fields=profile

These 2 calls can be merged into one with fields=profile,follow,owns

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani @Sachin-chaurasiya @ShaileshParmar11 lets make some progress here

**Comment by harshach** [comment]
@chirag-madlani @Sachin-chaurasiya if this is resolved lets close it out

**Comment by Sachin-chaurasiya** [comment]
@harshach, this is not done yet.
we checked both API calls and both are in different components for different purposes.
This(https://sandbox.open-metadata.org/api/v1/users/0cd4048d-ce07-4699-a86f-98ac45dbdb4d?fields=follows,owns) one is to get the user's own and followed data on the landing page.

The other one (https://sandbox.open-metadata.org/api/v1/users/name/harsha?fields=profile) is from the activity feed card to get the user profile picture, we are making this separate call because, in the activity feed, we only get entity reference for the user.

![Image](https://user-images.githubusercontent.com/59080942/234546774-59290c14-85e7-4c6c-80e7-3271c64a6239.png)

We caching the above response on the UI side to avoid multiple calls for the same user.

I was thinking if we could have a separate API for just fetching profile picture data something like below:


`/api/v1/user/{username}/profile-picture` - Request

Response : ![Image](https://user-images.githubusercontent.com/59080942/234546774-59290c14-85e7-4c6c-80e7-3271c64a6239.png)

**Comment by chirag-madlani** [comment]
@harshach closing it since not any false API is being made.
