### ISSUE TITLE
Fix activity feed dashboard link

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9128]
Activity feed from Metabase creates the link properly as `/dashboard/...`

In Looker we are creating it as `/table/...`

**Comment by aniketkatkar97** [comment]
As of now, we don't have a page dedicated to showing chart details, there won't be a proper link to redirect the user. 
We will handle this issue later as we are thinking about adding the chart details page.

**Comment by Ashish8689** [comment]
@mohityadav766 

 For the dashboard chart entity feed, we are not getting the correct entity link, for example, we have dashboard `sample_looker.customers` and it has charts `chart_1` and `chart_2`. so if we make any changes to `chart_1`, the change event is generated, however, the `about` attribute has the wrong entity link.

It has `<E::chart::sample_looker.chart_1>`, instead of `<E::chart::sample_looker.customers.chart_1>`

![image](https://github.com/open-metadata/OpenMetadata/assets/59080942/b0995a7f-af94-494b-ad20-cf39dd5873c4)
