### ISSUE TITLE
entity already exists

### ISSUE THREAD

**Issue by KevinParijs** [open-metadata/OpenMetadata#9155]
**Affected module**
Register a new account screen

**Describe the bug**
During a first step I created a first account with the same  first- and lastname together with a gmail address. Upon click "Create account" I got a message saying that the account has been created and the account needs to be activated via the activation mail.

During a second step I created a second account with the same first- and lastname together with a hotmail address. When clicking on "Create account" I get the error message `entity already exists`

**To Reproduce**

1. Navigate to http://localhost:8585
2. Click on Create Account
3. Fill in the form (for the first time)

- First Name: Example
- Last Name: Demo
- Email: demo@gmail.com

4. Click on Create Account
5. (Normally you should receive a message that the account has been created)
6. Create another (second) account

- First Name: Example
- Last Name: Demo
- Email: demo@hotmail.com

7. Click on Create Account
8. Now you should receive the error `entity already exists`

**Expected behavior**

**Version:**
 - OS: [e.g. iOS] Windows 10 machine
 - Python version: 3.10.8
 - OpenMetadata version: [e.g. 0.8] latest version running in a docker container
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@KevinParijs our take on account management here is that an organization where OpenMetadata deployed will have unique domain. Example , yelp.com they installed metadata and all of their users will signup with username@yelp.com. So we decided to use the username as unique constraint rather than the email address.  
In your case you are using hotmail.com and gmail.com with the same username "demo" it will throw an exception saying there can only one user exist

@chirag-madlani @Sachin-chaurasiya for such "Entity already exists" errors we should throw a better error from the UI . In this case A user with "demo" already exists.

**Comment by Sachin-chaurasiya** [comment]
The messages are coming from the backend, so assigning this issue to the backend team.

**Comment by harshach** [comment]
@Sachin-chaurasiya @chirag-madlani intent here is to throw better error from UI side, UI will give you generic entity already exists. But UI knows the context of it so modulate it to better error message that user can recognize

**Comment by chirag-madlani** [comment]
@harshach will check on UI side and let you of if backend support required at any place

**Comment by aniketkatkar97** [comment]
Checks to verify the message for different entities:
- [ ] User
- [ ] Team
- [ ] Query
- [ ] Bot
- [ ] Service
- [ ] Glossary
- [ ] Tag
- [ ] Roles
- [ ] Policy
- [ ] Rules
- [ ] Alert
- [ ] Test case
- [ ] Test suite
- [ ] Classification
